abdisere__intr & abbedissen abdiserer
abonnere__intr & vi abonnerer &
abortere__intr & hun aborterer &
absolvere__intr & han absolverer &
abstrahere__intr & formelen abstraherer &
adlyde__intr & soldatene adlyder &
agere__intr & vi agerer &
agglutinere__intr & bitene agglutinerer &
agitere__intr & aktivistene agiterer &
ake__intr & barna aker &
akkedere__intr & forhandlerne akkederer &
akkompagnere__intr & bandet akkompagnerer &
akkordere__intr & representantene akkorderer &
akselerere__intr & bilens hastighet akselererer &
aksjonere__intr & aktivistene aksjonerer &
aldres__intr & vi aldres &
allitterere__intr & verselinjene allittererer &
alternere__intr & deltagerne alternerer &
ambulere__intr & deltagerne ambulerer &
amme__intr & hun ammer &
ane__intr & vi aner &
ange__intr & blomstene anger &
angre__intr & vi angrer &
angripe__intr & vi angriper &
anke__intr & den dømte anker &
apokopere__intr & trøndersk apokoperer mye &
applaudere__intr & tilhørerne applauderer &
applikere__intr & han applikerer &
apportere__intr & hunden apporterer &
argumentere__intr & partene argumenterer fortsatt &
arrivere__intr & primadonnaen arriverer &
atrofiere__intr & stoffet atrofierer &
auke__intr & vi auker &
aure__intr & vi aurer &
avansere__intr & troppene avanserer &
avgå__intr & helseministeren avgår &
avkoble__intr & de avkobler på stranden &
avmønstre__intr & vi avmønstrer &
avreagere__intr & vi avreagerer &
avreise__intr & delegasjonen avreiser &
avruste__intr & stormaktene avruster &
avskalle__intr & malingen avskaller &
avspasere__intr & vi avspaserer &
avspore__intr & toget avsporer &
avstresse__intr & vi avstresser &
avta__intr & stormen avtar &
bable__intr & de babler &
bade__intr & vi bader &
bake__intr & vi baker &
bakke__intr & vi bakker &
balansere__intr & vi balanserer &
ballottere__intr & de ballotterer &
banke__intr & vi banker &
banne__intr & vi banner &
be__intr & vi ber &
bedres__intr & helsen bedres &
begeistre__intr & filmen begeistrer &
begynne__intr & vi begynner &
beinflyge__intr & vi beinflyr &
beite__intr & sauene beiter &
beklage__intr & jeg beklager &
belje__intr & mennene beljer &
bero__intr & saken beror &
berte__intr & bilen berter &
beskne__intr & vinen beskner &
bestemme__intr & vi bestemmer &
bestå__intr & institusjonen består &
besvime__intr & vi besvimer &
betale__intr & vi betaler &
betle__intr & de betler &
beve__intr & jorden bever &
bevre__intr & skikkelsen bevrer &
bie__intr & de fremmøtte bier &
bikke__intr & vogna bikker &
billettere__intr & sjåføren billetterer &
bite__intr & pirañaene biter &
bivuakkere__intr & soldatene bivuakkerer &
bjeffe__intr & hundene bjeffer &
bla__intr & leseren blar &
blaffe__intr & seilet blaffer &
blafre__intr & lysene blafrer &
blakne__intr & håret hans blakner &
bleikne__intr & ansiktene bleikner &
blekne__intr & ansiktene blekner &
blingse__intr & øynene blingser &
blinke__intr & lysene blinker &
blitse__intr & fotoapparatene blitser &
blogge__intr & deltagerne blogger &
blomstre__intr & fiolene blomstrer &
blote__intr & høvdingene bloter &
blues__intr & de mest generte blues &
blunde__intr & vaktene blunder &
blundesove__intr & han blundesover &
blunke__intr & de blunker &
blyges__intr & de forlovede blyges &
blø__intr & såret blør &
bløde__intr & såret bløder &
bløffe__intr & de bløffer &
blåne__intr & fjellene blåner &
blånekte__intr & de anklagede blånekter &
boble__intr & vannet bobler &
bokse__intr & deltagerne bokser &
bole__intr & aristokratiet boler &
bomme-1__intr & skyterne bommer &
boogie__intr & festdeltagerne boogier i vei &
bore__intr & bergverksarbeiderne borer &
bortfalle__intr & gjeldskravene bortfaller &
botanisere__intr & skogsforvalteren botaniserer &
botne__intr & båtkjølen botner &
botnfryse__intr & sjøen botnfryser &
bowle__intr & bowlerne bowler &
bramme__intr & skrythalsen brammer &
brase__intr & festdeltagerne braser &
braske__intr & festdeltagerne brasker &
bratne__intr & fjellsiden bratner &
braute__intr & festdeltagerne brauter &
bravere__intr & festdeltagerne braverer &
breke__intr & sauene breker &
brekke__intr & grenen brekker &
bremse__intr & bilen bremser &
brenne__intr & huset brenner &
breste__intr & knoppen brester &
brettsegle__intr & de brettsegler &
brettseile__intr & de brettseiler &
brevveksle__intr & de brevveksler &
briljere__intr & de briljerer &
briste__intr & knoppen brister &
brodere__intr & vi broderer &
bronsere__intr & denne butikken bronserer &
brosjere__intr & denne butikken brosjerer &
brotne__intr & isen brotner &
brumle__intr & husverten brumler &
brumme__intr & bjørnen brummer &
bruse__intr & fossen bruser &
bryte__intr & sumobryterne bryter &
brytes__intr & interessene brytes &
bråbremse__intr & bilen bråbremser &
bråke__intr & barna bråker &
bråne__intr & isen bråner &
bråstanse__intr & toget bråstanser &
bugne__intr & fruktkurvene bugner &
bukke__intr & hovmesteren bukker &
buklande__intr & seilflyet buklander &
buldre__intr & stenmassene buldrer &
bulke__intr & bilen bulker &
bulne__intr & sidene bulner &
bunkre__intr & båtene bunkrer &
bunnfryse__intr & sjøene bunnfryser &
bure__intr & oksen burer &
bygge__intr & statsselskapene bygger &
bysse__intr & moren bysser &
bytte__intr & deltagerne bytter &
bære__intr & søstrene bærer &
bæsje__intr & barna bæsjer &
bølge__intr & havet bølger &
bølgje__intr & havet bølgjer &
båre__intr & havet bårer &
campe__intr & turistene camper &
celebrere__intr & gjestene celebrerer &
cha-cha__intr & tilhengerne cha-chaer muntert &
changere__intr & de changerer & shapeshifteren changerer &
chatte__intr & de chatter &
chevrotere__intr & sangeren chevroterer &
choke__intr & motoren choker &
clinche__intr & bokserne clincher &
clutche__intr & sjåføren clutcher &
cruise__intr & de ligger og cruiser &
daffe__intr & dagdriverne daffer &
dagdrømme__intr & dagdriverne dagdrømmer &
dale__intr & ballongen daler &
dampe__intr & klærne damper &
dampkoke__intr & potetene dampkoker &
dangle__intr & julepynten dangler &
daue__intr & de dauer som fluer &
debattere__intr & debattantene debatterer &
debutere__intr & skuespillerne debuterer &
deejaye__intr & han deejayer om kveldene &
defilere__intr & kompaniet defilerer &
deflatere__intr & dollaren deflaterer &
dekke-2__intr & hunden dekker &
deklamere__intr & skuespilleren deklamerer &
dekortere__intr & banken dekorterer &
dele__intr & de fattige deler &
deles__intr & området deles &
delirere__intr & den reddede delirerer &
delje__intr & dørvakten deljer &
delta__intr & alle de fremmøtte deltar &
demisjonere__intr & statsråden demisjonerer &
demonstrere__intr & opprørerne demonstrerer &
demre__intr & dagen demrer &
deppe__intr & taperne depper &
derivere__intr & logikere deriverer &
desertere__intr & soldatene deserterer &
desinformere__intr & myndighetene desinformerer &
desorientere__intr & myndighetene desorienterer &
detonere__intr & bomben detonerer &
dette__intr & passasjerene detter &
deviere__intr & observasjonene devierer &
die__intr & moren dier &
differere__intr &  testene differerer &
diffundere__intr & lyset diffunderer &
dikte__intr & denne generasjonen dikter &
dille__intr & lærerne diller &
dilte__intr & politikerne dilter &
dimme__intr & soldatene dimmer &
dinere__intr & herskapene dinerer &
dingle__intr & korkene dingler &
dirre__intr & veggene dirrer &
disputere__intr & professorene disputerer &
disse__intr & barna disser &
dissentere__intr & professorene dissenterer &
dissonere__intr & klangene dissonerer &
divergere__intr & tolkningene divergerer &
djupne__intr & elva djupner &
dobbeltfeile__intr & han dobbeltfeiler &
dobbeltklikke__intr & han dobbeltklikker &
dogge__intr & vinduene dogger &
dokke__intr & skipet dokker &
dorge__intr & fiskerne dorger &
dorme__intr & de dormer &
dosere__intr & de doserer &
dratte__intr & de dratter &
dregge__intr & fiskerne dregger &
drible__intr & spilleren dribler &
drikke__intr & konsulen drikker &
drille__intr & oljeselskapene driller &
drite__intr & deltagerne driter &
drive__intr & båten driver &
drodle__intr & tilhørerne drodler &
drukne__intr & gutten drukner &
dryppe__intr & grenene drypper &
drypptørke__intr & genseren drypptørker &
drysse__intr & de drysser &
drømme__intr & de drømmer &
drønne__intr & skuddene drønner &
drøse__intr & de drøser &
drøvtygge__intr & de drøvtygger &
dubbe__intr & filmfremviserne dubber &
duellere__intr & rivalene duellerer &
dufte__intr & blomstene dufter &
duge__intr & innsatsen duger &
dugge__intr & vinduene dugger &
dukke__intr & de dukker &
dumpe__intr & elevene dumper &
dundre__intr & kanonene dundrer &
dunke__intr & de dunker &
dunste__intr & de dunster &
duppe__intr & han sitter og dupper &
dure__intr & maskinene durer &
dusje__intr & spillerne dusjer &
duve__intr & seilbåtene duver &
dvele__intr & deltagerne dveler &
dø__intr & plantene dør &
dønne__intr & kanonene dønner &
døse__intr & pasienten døser &
dåne__intr & de dåner &
egge__intr & rytmene egger &
eime__intr & kjelleren eimer &
eire__intr & kopperet eirer &
ejakulere__intr & han ejakulerer &
eksellere__intr & gullpalmevinnerne eksellerer &
eksfoliere__intr & løvet eksfolierer &
ekshalere__intr & røkeren ekshalerer &
eksistere__intr & gudene eksisterer &
eksklamere__intr & skuespilleren eksklamerer &
ekspandere__intr & bedriften ekspanderer &
eksperimentere__intr & forskerne eksperimenterer &
ekspirere__intr & tillatelsen ekspirerer &
eksplodere__intr & de eksploderer &
ekspostulere__intr & de rammede ekspostulerer &
ekstemporere__intr & de ekstemporerer &
eldes__intr & pensjonistene eldes &
elske__intr & de elskende elsker &
embarkere__intr & de reisende embarkerer &
emigrere__intr & flyktningene emigrerer &
emittere__intr & lydinstrumentene emitterer &
emulgere__intr & stoffet emulgerer &
ende__intr & fortellingen ender &
enes__intr & partene enes &
engasjere__intr & fortellingen engasjerer &
erigere__intr & penisen erigerer &
erodere__intr & jordsmonnet eroderer &
ese__intr & blandingen eser &
eskalere__intr & opptøyene eskalerer &
eskapere__intr & tyvene eskaperer &
estetisere__intr & kunstnerskolen estetiserer &
ete__intr & han eter &
etterklinge__intr & lyden etterklinger &
evangelisere__intr & apostlene evangeliserer &
evaporere__intr & dampen evaporerer &
exe__intr & de exer &
fable__intr & dikterne fabler &
fabulere__intr & dikterne fabulerer &
fallere__intr & sportssjernene fallerer &
falme__intr & stoffene falmer &
famle__intr & etterforskerne famler &
fangste__intr & de fangster &
fantasere__intr & de fantaserer &
fantegå__intr & barna fantegår &
farte__intr & omstreiferne farter &
fascinere__intr & landskapet fascinerer &
faste__intr & katolikkene faster &
fastne__intr & knutene fastner &
feide__intr & landsbyene feider &
feie__intr & feieren feier &
feile__intr & politikerne feiler &
feire__intr & tilhengerne feirer &
feitne__intr & de feitner &
fekte__intr & duellantene fekter &
fenge__intr & refrengene fenger &
ferdes__intr & selgerne ferdes &
ferge__intr & fergemannen ferger &
feriere__intr & de ferierer &
ferje__intr & de ferjer &
fermentere__intr & saften fermenterer &
feste__intr & ungdommene fester &
fetne__intr & fasanen fetner &
fibrillere__intr & muskelen fibrillerer &
fighte__intr & konkurrentene fighter &
figurere__intr & navnet figurerer &
fikle__intr & de fikler &
filere__intr & syersken filerer &
filetere__intr & de fileterer &
filme__intr & de filmer &
filosofere__intr & de filosoferer &
fingermale__intr & elevene fingermaler &
fingre__intr & de fingrer &
finnes__intr & ulver finnes &
finregne__intr & de finregner &
finrekne__intr & de finrekner &
finte__intr & spillerne finter &
fire__intr & de firer &
fise__intr & de fiser &
fisjonere__intr & atomkjernene fisjonerer &
fiske__intr & fiskerne fisker &
fisle__intr & fislene fisler &
fjamse__intr & gjestene fjamser &
fjase__intr & gjestene fjaser &
fjellklatre__intr & turistene fjellklatrer &
fjerte__intr & han fjerter &
fjeske__intr & de fjesker &
fjolle__intr & gjestene fjoller &
fjuske__intr & elevene fjusker &
fjære__intr & madrassene fjærer &
fjøre__intr & madrassene fjører &
flagge__intr & innbyggerne flagger &
flagre__intr & seilene flagrer &
flakke__intr & blikket hans flakker &
flakne__intr & de flakner &
flakse__intr & vingene flakser &
flane__intr & flanørene flaner &
flanere__intr & dikterne flanerer &
flare__intr & lyset flarer &
flasse__intr & håret flasser &
flatne__intr & profilen flatner &
flaue__intr & vinden flauer &
fleipe__intr & guttene fleiper &
flekse__intr & musklene flekser &
flektere__intr & verbene flekterer &
flimre__intr & bildene flimrer &
flippe__intr & foreldrene flipper &
flire__intr & mennene flirer &
flokse__intr & kurtisanene flokser &
flomme__intr & vannet flommer &
floppe__intr & kandidatene flopper &
floragrafere__intr & gratulantene floragraferer &
florere__intr & ryktene florerer &
fluktuere__intr & verdiene fluktuerer &
fluorescere__intr & stoffet fluorescerer &
fly__intr & fuglene flyr &
flyge__intr & fuglene flyger &
flytte__intr & naboene flytter &
flø__intr & de flør &
flømme__intr & de flømmer &
flørte__intr & de flørter &
fløyte__intr & dommeren fløyter &
flåse__intr & ungdommene flåser &
fnise__intr & jentene fniser &
fnyse__intr & naboene fnyser &
fokusere__intr & fotografen fokuserer &
fole__intr & hesten foler &
folne__intr & blomstene folner &
fomle__intr & myndighetene fomler &
forblø__intr & pasienten forblør &
forbrenne__intr & næringsstoffer forbrenner &
fordampe__intr & vannet fordamper &
forderves__intr & man forderves i sin sjel &
fordufte__intr & gjestene fordufter &
fordunste__intr & fuktigheten fordunster &
foredra__intr & skuespilleren foredrar &
forefalle__intr & slike ting forefaller &
forefinnes__intr & eksemplarer forefinnes &
foregå__intr & seansen foregår &
forekomme__intr & slike ting forekommer &
foreldes__intr & ordene foreldes &
forelese__intr & professoren foreleser &
foreligge__intr & beviset foreligger &
forfalle__intr & bygningene forfaller &
forglasses__intr & substansen forglasses &
forgrenes__intr & elveløpet forgrenes &
forgroves__intr & morsomhetene forgroves &
forgå__intr & menneskerasen forgår &
forhandle__intr & partene forhandler &
forhandsstemme__intr & de forhandsstemmer &
forherdes__intr & sinnene forherdes &
forhåndsstemme__intr & vi forhåndsstemmer &
forklare__intr & boken forklarer &
forkomme__intr & reinkalvene forkommer &
forkulle__intr & trestykkene forkuller &
forkynne__intr & prestene forkynner &
forlikes__intr & partene forlikes &
forlise__intr & båten forliser &
forlyde__intr & ryktene forlyder &
forløpe__intr & dagen forløper &
forminskes__intr & volumet forminskes &
formolde__intr & plantene formolder &
formulde__intr & plantene formulder &
forplikte__intr & tilliten forplikter &
forrette__intr & biskopen forretter &
forringes__intr & kvaliteten forringes fort &
forsimples__intr & utformingen forsimples &
forske__intr & de forsker &
forslå__intr & dette bidraget forslår &
forsteines__intr & formasjonen forsteines &
forstenes__intr & formasjonen forstenes &
forstumme__intr & røstene forstummer &
forstøve__intr & frøene forstøver &
forstå__intr & rådgiveren forstår &
fortne__intr & klokken fortner &
fortvile__intr & ofrene fortviler &
fortørkes__intr & jordsmonnet fortørkes &
forulykke__intr & mannskapet forulykker &
forvelle__intr & grønnsakene forveller &
forverres__intr &  tilstanden forverres &
forvitre__intr & statuene forvitrer &
fosforescere__intr & svovelforbindelser fosforescerer ikke &
fosskoke__intr & potetene fosskoker &
fossro__intr & roerne fossror &
fotografere__intr & journalistene fotograferer &
frafalle__intr & advokaten frafaller &
framkomme__intr & løsningen framkommer &
frasere__intr & skuespillerne fraserer &
fraternisere__intr & deltagerne fraterniserer &
fremkomme__intr & konsekvensene fremkommer &
frese__intr & katten freser &
fri__intr & han frir &
frilanse__intr & kunstnerne frilanser &
friskne__intr & vinden friskner &
frondere__intr & organisasjonene fronderer &
frukte__intr & tiltakene frukter &
fryse__intr & tilskuerne fryser &
frøse__intr & hesten frøser &
fråde__intr & vannet fråder &
fråsse__intr & åtselfuglene fråsser &
fråtse__intr & åtselfuglene fråtser &
fundere__intr & tenkeren funderer &
fungere__intr & oppskriften fungerer &
funke__intr & metoden funker &
funkle__intr & stjernene funkler &
funksjonere__intr & metoden funksjonerer &
furasjere__intr & deltagerne furasjerer &
furte__intr & deltagerne furter &
fusjonere__intr & firmaene fusjonerer &
fuske__intr & deltagerne fusker &
fyllekjøre__intr & studentene fyllekjører &
fyre__intr & husholdningene fyrer &
fæle__intr & ungene fæler &
føde__intr & kvinnen føder &
følle__intr & hoppen føller &
føyke__intr & snøen føyker &
gakke__intr & gjessene gakker &
galdre__intr & trollkvinnene galdrer &
gale__intr & hanen galer &
galoppere__intr & hestene galopperer &
gamble__intr & spillerne gambler &
gande__intr & samene gander &
ganne__intr & trollmannen ganner &
gantes__intr & naboene gantes &
gape__intr & tilskuerne gaper &
gaple__intr & tilskuerne gapler &
gapskratte__intr & tilskuerne gapskratter &
garnisonere__intr & majoren garnisonerer &
garpe__intr & guttene garper &
gate-krasje__intr & gutta gate-krasjer &
gauke__intr & smuglerne gauker &
gaule__intr & guttene gauler &
geipe__intr & guttene geiper &
gestikulere__intr & deltagerne gestikulerer &
gidde__intr & deltagerne gidder ikke &
gigge__intr & deltagerne gigger &
gildre__intr & festkomiteen gildrer &
gimpe__intr & syersken gimper &
gisne__intr & deltagerne gisner &
gispe__intr & deltagerne gisper &
gisse__intr & deltagerne gisser &
gjalle__intr & hornene gjaller &
gjelde__intr & lovene gjelder &
gjelle__intr & hornene gjeller &
gjengro__intr & blomsterbedene gjengror &
gjenlyde__intr & eksplosjonene gjenlyder &
gjenmæle__intr & de ansatte gjenmæler &
gjenoppblusse__intr & mapene gjenoppblusser &
gjenopplives__intr & virksomheten gjenopplives &
gjenoppstå__intr & de døde gjenoppstår &
gjenstå__intr & oppgavene gjenstår &
gjespe__intr & tilhørerne gjesper &
gjette__intr & deltagerne gjetter &
gjære__intr & blandingen gjærer &
gjø__intr & hunden gjør &
gjøgle__intr & gjøglerne gjøgler &
gjøle__intr & smigrerne gjøler &
gla__intr & solen glar &
glamme__intr & hundene glammer &
glane__intr & turistene glaner &
glefse__intr & ulvene glefser &
gleppe__intr & taket glepper &
gli__intr & vogna glir &
glide__intr & sleden glider &
glidefly__intr & deltagerne glideflyr &
glideflyge__intr & deltagerne glideflyger &
glime__intr & lyktene glimer &
glimre__intr & metallet glimrer &
glimte__intr & fyrlykten glimter &
glinse__intr & gaflene glinser &
glipe__intr & døråpningen gliper &
glippe__intr & taket glipper &
glire__intr & øynene glirer &
glise__intr & guttene gliser &
glitre__intr & glassene glitrer &
glo__intr & tilskuerne glor &
glore__intr & tilskuerne glorer &
glø__intr & gnistene glør &
gløde__intr & vedstykkene gløder &
gløtte__intr & naboene gløtter &
gnage__intr & rottene gnager &
gnaldre__intr & deltagerne gnaldrer &
gneldre__intr & nabokona gneldrer &
gnelle__intr & grisen gneller &
gnisle__intr & filbladet gnisler &
gnisse__intr & hjulene gnisser &
gniste__intr & telegrafisten gnister &
gnistre__intr & øynene gnistrer &
gny__intr & fossefallet gnyr &
gnåle__intr & politikerne gnåler &
gomle__intr & guttene gomler &
gove__intr & snøen gover &
graduere__intr & studentene graduerer &
grafse__intr & avisene grafser &
grase__intr & kyrne graser &
grassere__intr & villstyringene grasserer &
grave__intr & maskinene graver &
gravitere__intr & gjenstandene graviterer &
gremmes__intr & hun gremmes &
gresse__intr & kyrne gresser &
grine__intr & taperne griner &
grise__intr & gjestene griser &
grisne__intr & bøtta grisner &
gro__intr & trærne gror &
groove__intr & partygjestene groover &
grope__intr & maven groper &
gruble__intr & filosofene grubler &
grunne__intr & båten grunner &
grunnstøte__intr & båtene grunnstøter &
gry__intr & dagen gryr &
grynte__intr & grisene grynter &
grø__intr & blomstene grør &
grøde__intr & marken grøder &
grøfte__intr & bøndene grøfter &
grønke__intr & trærne grønker &
grønkes__intr & trærne grønkes &
grønnes__intr & trærne grønnes &
grønske__intr & overflaten grønsker &
grøsse__intr & tilskuerne grøsser &
gråne__intr & håret gråner &
gråte__intr & konene gråter &
gulne__intr & løvet gulner &
gulpe__intr & tilskuerne gulper &
gurgle__intr & han gurgler &
gurpe__intr & gutten gurper &
gymnastisere__intr & gymnastene gymnastiserer &
gynge__intr & barna gynger &
gyse__intr & tilskuerne gyser &
gyte__intr & fisken gyter &
gøyse__intr & vannet gøyser &
hacke__intr & cyberbandittene hacker &
hagle__intr & isbitene hagler &
haike__intr & ungdommene haiker &
hakke__intr & hakkespettene hakker &
hale__intr & mannskapet haler &
halle__intr & eiendommen haller &
hallusinere__intr & deltagerne hallusinerer &
halse__intr & hundene halser &
halte__intr & krigsveteranen halter &
halvsove__intr & elevene halvsover &
hamre__intr & snekkeren hamrer &
hamstre__intr & innbyggerne hamstrer &
handhelse__intr & slektningene handhelser &
handhilse__intr & slektningene handhilser &
handle__intr & politiet handler &
handse__intr & forsvarsspilleren handser &
hangle__intr & pasienten hangler &
hardne__intr & frontene hardner &
hardtrene__intr & spillerne hardtrener &
harke__intr & motoren harker &
harmes__intr & beboerne harmes &
harmonere__intr & målene harmonerer &
harselere__intr & kritikerne harselerer &
harskne__intr & tranen harskner &
harve__intr & bonden harver &
haste__intr & saksbehandlerne haster &
hauke__intr & redningsmannskapene hauker &
havarere__intr & båten havarerer &
heade__intr & midtstopperen header &
heie__intr & tilskuerne heier &
heise__intr & kranene heiser &
heitne__intr & ovnen heitner &
hekke__intr & fuglene hekker &
hekle__intr & bestemor hekler &
hekse__intr & heksene hekser &
helle__intr & dagen heller &
hende__intr & slikt hender &
henge__intr & gardinene henger &
henstå__intr & saken henstår &
herdes__intr & metallet herdes &
herdne__intr & metallet herdner &
herje__intr & soldatene herjer &
hesje__intr & onnefolket hesjer &
hestehandle__intr & konkurrentene hestehandler &
hetne__intr & vannet hetner &
hikke__intr & hun hikker &
hikste__intr & han hikster &
hikstegråte__intr & de hikstegråter &
hildre__intr & fjellene hildrer &
hilse__intr & gjestene hilser &
hinke__intr & gutten hinker &
hive__intr & skuta hiver &
hjelpe__intr & medisinen hjelper &
holde__intr & demningen holder &
hore__intr & gjestene horer &
horse__intr & hingstene horser &
horve__intr & bonden horver &
hospitere__intr & elevene hospiterer &
hoste__intr & pasienten hoster &
hote__intr & husverten hoter &
hovere__intr & vinnerne hoverer &
hovmesterere__intr & han hovmestererer &
hovne__intr & armen hovner &
hue__intr & tilskuerne huer &
hulke__intr & de sørgende hulker &
humpe__intr & vogna humper &
humre__intr & tilhørerne humrer &
hungre__intr & flyktninene hungrer &
hurrae__intr & mengden hurraer &
husere__intr & bandittene huserer &
huske__intr & barna husker &
hustre__intr & flyktningene hustrer &
hutre__intr & flyktningene hutrer &
hvelve__intr & båten hvelver &
hvese__intr & kattene hveser &
hvile__intr & foreldrene hviler &
hvine__intr & kulene hviner &
hviske__intr & deltagerne hvisker &
hvitne__intr & fjellviddene hvitner &
hykle__intr & vasallene hykler &
hyle__intr & ulvene hyler &
hyperventilere__intr & han hyperventilerer &
hysje__intr & læreren hysjer &
hysse__intr & læreren hysser &
høkre__intr & spekulantene høkrer &
hølje__intr & regnet høljer &
høre__intr & vi hører &
høres__intr & deltagerne høres &
høve__intr & fremgangsmåten høver &
håndhilse__intr & deltagerne håndhilser &
hånflire__intr & mobberne hånflirer &
hånle__intr & mobberne hånler &
idest__intr & ungene idest ikke &
idke__intr & de ansatte idker &
illgjø__intr & hundene illgjør &
illhuie__intr & klatrerne illhuier &
illskrike__intr & barna illskriker &
immigrere__intr & flyktningene immigrerer &
implodere__intr & økonomien imploderer &
improvisere__intr & skuespillerne improviserer &
inhalere__intr & røykerne inhalerer &
inklinere__intr & linjen inklinerer &
innflytte__intr & naboene innflytter neste uke &
innovere__intr & industrien innoverer &
innpassere__intr & soldatene innpasserer &
innrapportere__intr & vakten innrapporterer &
innrykke__intr & fienden innrykker &
innskrenke__intr & selskapene innskrenker &
innånde__intr & pasienten innånder &
inseminere__intr & de inseminerer &
insistere__intr & demonstrantene insisterer &
interagere__intr & deltagerne interagerer &
interferere__intr & lydfrekvensene interfererer &
interpellere__intr & representantene interpellerer &
interpolere__intr & matematikerne interpolerer &
intervenere__intr & kontrollkomiteen intervenerer &
intonere__intr & dirigenten intonerer &
intrigere__intr & diplomatene intrigerer &
introspektere__intr & psykologene introspekterer &
inventere__intr & oppfinnerne inventerer &
invitere__intr & kommunen inviterer &
irisere__intr & stoffet iriserer &
ironisere__intr & kritikerne ironiserer &
irre__intr & metallet irrer &
ise__intr & vannene iser &
isne__intr & vannet isner &
istemme__intr & forsamlingen istemmer &
ivre__intr & forsamlingen ivrer &
jabbe__intr & forsamlingen jabber &
jalme__intr & forsamlingen jalmer &
jamme__intr & jazzmusikerne jammer &
jamre__intr & de sårede jamrer &
jasse__intr & musikerne jasser &
jatte__intr & forsamlingen jatter &
jazze__intr & musikerne jazzer &
jibbe__intr & seilet jibber &
jodle__intr & tyrolerne jodler &
jogge__intr & spillerne jogger &
joike__intr & samene joiker &
jorte__intr & kuene jorter &
jubilere__intr & klubben jubilerer &
juble__intr & forsamlingen jubler &
jukse__intr & elevene jukser &
jumpe__intr & hopperne jumper &
junke__intr & ungdommene junker &
kadreie__intr & båtene kadreier &
kakle__intr & hønene kakler &
kaldflire__intr & duellantene kaldflirer &
kaldskratte__intr & tilskuerne kaldskratter &
kaldsmi__intr & bonden kaldsmir &
kaldsvette__intr & duellantene kaldsvetter &
kalkulere__intr & investorene kalkulerer &
kalle__intr & pliktene kaller &
kalligrafere__intr & kunstnerne kalligraferer &
kalve__intr & isbreen kalver &
kampere__intr & turistene kamperer &
kandidere__intr & politikerne kandiderer &
kannelere__intr & arkitektene kannelerer &
kante__intr & syersken kanter &
kantre__intr & båten kantrer &
kapitulere__intr & fienden kapitulerer &
kappdrikke__intr & deltagerne kappdrikker &
kappes__intr & deltagerne kappes &
kappkjøre__intr & deltagerne kappkjører &
kapseise__intr & båten kapseiser &
karde__intr & spinneriet karder &
kastebytte__intr & kameratene kastebytter &
katekisere__intr & prestene katekiserer &
kaue__intr & huldra kauer &
kauke__intr & gjeterne kauker &
kausjonere__intr & advokatene kausjonerer &
kave__intr & de badende kaver &
keivle__intr & begynnerne keivler &
kike__intr & tilskuerne kiker &
kikne__intr & ungen kikner &
kikre__intr & styrmannen kikrer &
kikse__intr & barna kikser &
kime__intr & klokkene kimer &
kippe__intr & båten kipper &
kisle__intr & stoffet kisler &
kitle__intr & stoffet kitler
kive__intr & deltagerne kiver &
kives__intr & deltagerne kives &
kjangse__intr & de kjangser &
kjase__intr & deltagerne kjaser &
kjave__intr & deltagerne kjaver &
kjederøyke__intr & de kjederøyker &
kjee__intr & geitene kjeer &
kjefte__intr & gårdeieren kjefter &
kjekle__intr & investorene kjekler &
kjempe__intr & motstanderne kjemper &
kjerve__intr & bonden kjerver &
kjese__intr & budeia kjeser &
kjølne__intr & været kjølner &
kjøpslå__intr & interessentene kjøpslår &
klabbe__intr & skiene klabber &
klaffe__intr & tidspunktet klaffer &
klage__intr & kundene klager &
klake__intr & vanndammen klaker &
klakke__intr & støvlene klakker &
klampe__intr & støvlene klamper &
klappe__intr & tilskuerne klapper &
klapre__intr & tennene klaprer &
klare__intr & båten klarer &
klarne__intr & været klarner &
klatre__intr & turistene klatrer &
klatte__intr & barna klatter &
klattemale__intr & barna klattemaler &
klebe__intr & limbåndet kleber &
klemte__intr & ringeklokken klemter &
klenge__intr & beundrerne klenger &
klikke__intr & pistolen klikker &
klimpre__intr & gitaristen klimprer &
kline__intr & kjærestene kliner &
klinge__intr & bjellene klinger &
klingre__intr & glassbitene klingrer &
klinke__intr & glassene klinker &
klirre__intr & glassene klirrer &
klisse__intr & fiskeskinnet klisser &
klive__intr & guttene kliver &
klore__intr & kattene klorer &
klovne__intr & gjøglerne klovner &
klubbe__intr & dommeren klubber &
kludre__intr & nybegynnerne kludrer &
klukke__intr & bekken klukker &
klukkle__intr & tilhørerne klukkler &
klundre__intr & arbeiderne klundrer &
klunke__intr & gitaristene klunker &
klusse__intr & nybegynnerne klusser &
klynke__intr & ofrene klynker &
klyve__intr & klatrerne klyver &
klø__intr & såret klør &
kløne__intr & de kløner &
kløtsje__intr & sjåføren kløtsjer &
kløvne__intr & artistene kløvner &
knake__intr & grenene knaker &
knalle__intr & fyrverkeriene knaller &
knappe__intr & bevilgningene knapper &
knarke__intr & hippiene knarker &
knase__intr & singelen knaser &
knatre__intr & maskingeværene knatrer &
knatte__intr & hakkespettene knatter &
knege__intr & gnieren kneger &
knegge__intr & hestene knegger &
kneise__intr & rytterstatuene kneiser &
knekke__intr & kvisten knekker &
knele__intr & tilhørerne kneler &
knepre__intr & storken kneprer &
knikse__intr & tjemestepiken knikser &
kniple__intr & syersken knipler &
knipse__intr & gjestene knipser &
knirke__intr & plankene knirker &
knise__intr & jentene kniser &
knisle__intr & latteren knisler &
knistre__intr & oldingen knistrer &
knitre__intr & flammene knitrer &
knoge__intr & tømmerhuggerne knoger &
knote__intr & byfolkene knoter &
knuffe__intr & konkurrentene knuffer &
knulle__intr & kjærestene knuller &
knurre__intr & hunden knurrer &
knuspe__intr & apparatet knusper &
knuspre__intr & apparatet knusprer &
kny__intr & kritikerne knyr &
knyste__intr & tysteren knyster &
koagulere__intr & blodet koagulerer &
koke__intr & vannet koker &
kokettere__intr & forfatterne koketterer &
kokkelere__intr & kokkene kokkelerer &
kollabere__intr & maratonløperen kollaberer &
kollaborere__intr & gruppene kollaborerer &
kollapse__intr & broen kollapser &
kolle__intr & tømmerhuggerne koller &
kollidere__intr & togene kolliderer &
kollokvere__intr & studentene kollokverer &
kollsegle__intr & båten kollsegler &
kollseile__intr & båten kollseiler &
kommunisere__intr & de kommuniserer &
kompe__intr & gitaristene komper &
kompostere__intr & husholdningen komposterer &
kompromisse__intr & partene kompromisser &
kondensere__intr & dampen kondenserer &
kondolere__intr & vi kondolerer &
konferere__intr & partene konfererer &
kongruere__intr & ordene kongruerer &
konke__intr & bedriften konker &
konkludere__intr & foredragsholderen konkluderer &
konkurrere__intr & naboklubbene konkurrerer &
konsertere__intr & orkesteret konserterer &
konspirere__intr & partene konspirerer &
kontinuere__intr & studentene kontinuerer &
kontrastere__intr & farvene kontrasterer &
kontre__intr & laget kontrer &
konvergere__intr & linjene konvergerer &
konversere__intr & gjestene konverserer &
konvertere__intr & menonittene konverterer &
kooperere__intr & firmaene koopererer &
kope__intr & tilskuerne koper &
kopulere__intr & dyrene kopulerer &
kore__intr & sangerne korer &
koreografere__intr & koreografen koreograferer &
korrespondere__intr & forfatterne korresponderer &
korrodere__intr & ledningene korroderer &
kortne__intr & dagene kortner &
kose__intr & kjærestene koser &
koseprate__intr & naboene koseprater &
koste-1__intr & anstrengelsen koster &
kovne__intr & fiskene kovner &
kramse__intr & han kramser &
krangle__intr & deltagerne krangler &
krasje__intr & bilene krasjer &
krasjlande__intr & flyet krasjlander &
krasle__intr & rottene krasler &
kraume__intr & husmennene kraumer &
kravle__intr & ungene kravler &
kremte__intr & mannen kremter &
krenge__intr & båten krenger &
krepere__intr & dyrene kreperer &
krepse__intr & guttene krepser &
krible__intr & bena kribler &
krige__intr & folkene kriger &
krikle__intr & barna krikler &
krille__intr & klærne kriller &
krisle__intr & gresstråene krisler &
kritle__intr & gresstråene kritler &
krokere__intr & landmålerne krokerer &
krokne__intr & ryggen krokner &
krongle__intr & maurene krongler &
kronikkere__intr & forfatteren kronikkerer &
krote__intr & elevene kroter &
krungle__intr & ungene krungler &
kruse__intr & støvet kruser &
kry__intr & maurene kryr &
krympe__intr & klærnw krymper &
krysse__intr & linjene krysser &
krysses__intr & dyrene krysses &
krøkne__intr & kvistene krøkner &
krølle__intr & stoffet krøller &
kråle__intr & svømmerne kråler &
kukelure__intr & mannen kukelurer &
kullsegle__intr & båten kullsegler &
kullseile__intr & båten kullseiler &
kulminere__intr & stormen kulminerer &
kulse__intr & vandreren kulser &
kumulere__intr & velgerne kumulerer &
kure__intr & pasienten kurer &
kurre__intr & duene kurrer &
kursere__intr & pengesedlene kurserer &
kuvende__intr & politikerne kuvender &
kvakke__intr & gjessene kvakker &
kvamne__intr & gutten kvamner &
kvede__intr & konene kveder &
kvekke__intr & froskene kvekker &
kvelde__intr & arbeiderne kvelder &
kveles__intr & plantene kveles &
kvelve__intr & båten kvelver &
kveppe__intr & kona kvepper &
kverulere__intr & debattantene kverulerer &
kverve__intr & bildene kverver &
kvese__intr & kattene kveser &
kvile__intr & deltagerne kviler &
kvilte__intr & venninnene kvilter &
kvine__intr & hengslene kviner &
kvinke__intr & hunden kvinker &
kvisse__intr & journalistene kvisser &
kvitne__intr & tøyet kvitner &
kvitre__intr & fuglene kvitrer &
kvittere__intr & mottageren kvitterer &
kysse__intr & kjærestene kysser &
kyte__intr & bøndene kyter &
kødde__intr & gutta kødder &
køe__intr & bankkundene køer &
køye__intr & sjøgutten køyer &
kåsere__intr & forfatteren kåserer &
lakke__intr & klokka lakker &
laksere__intr & pasienten lakserer &
lale__intr & gjeterne laler &
lalle__intr & fylliken laller &
lamme__intr & sauene lammer &
lande__intr & flyet lander &
larme__intr & vognene larmer &
lauve__intr & bonden lauver &
lave__intr & snøen laver &
layoute__intr & arbeidsgiverne layouter &
le__intr & deltagerne ler &
ledes__intr & hoffdamene ledes &
leies__intr & hoffdamene leies &
leike__intr & barna leiker &
leite__intr & mannskapene leiter &
leke__intr & barna leker &
lekke__intr & rørene lekker &
lenges__intr & kjærestene lenges &
lense__intr & maskinene lenser &
lepe__intr & gardinen leper &
lese__intr & barna leser &
lespe__intr & gutten lesper &
lete__intr & mannskapene leter &
letne__intr & skyene letner &
lette__intr & flyet letter &
leve__intr & de savnede lever &
lide__intr & de fattige lider &
ligge__intr & pasienten ligger &
ligne__intr & søsknene ligner &
lignifisere__intr & plantene lignifiserer &
likne__intr & søsknene likner &
lindre__intr & salven lindrer &
linnkoke__intr & eggene linnkoker &
ljome__intr & klokkene ljomer &
ljuge__intr & ledelsen ljuger &
loe__intr & sokkene loer &
loffe__intr & de arbeidsløse loffer &
logre__intr & hunden logrer &
lokke-1__intr & reklamene lokker &
lombardere__intr & de lombarderer &
loope__intr & programmet looper &
losse__intr & skipet losser &
love__intr & ledelsen lover &
lue__intr & flammene luer &
lugge__intr & skiene lugger &
luke__intr & gartneren luker &
lulle__intr & sangen luller &
lune__intr & fjellveggen luner &
lunsje__intr & deltagerne lunsjer &
lyde__intr & signalet lyder &
lye__intr & skogen lyer &
lyge__intr & ledelsen lyger &
lykkes__intr & forsøket lykkes &
lyne__intr & øynene lyner &
lyse__intr & lampene lyser &
lyseres__intr & blandingen lyseres &
lysne__intr & himmelen lysner &
lystre__intr & soldatene lystrer &
lytte__intr & tilhørerne lytter &
lyve__intr & ledelsen lyver &
løsne__intr & båndene løsner &
løye__intr & vinden løyer &
låte__intr & harpen låter &
male__intr & katten maler &
mangle__intr & dokumentene mangler &
mankere__intr & midlene mankerer &
manudusere__intr & magisteren manuduserer &
marme__intr & dønningene marmer &
mase__intr & innbyggerne maser &
maskinskrive__intr & sekretæren maskinskriver &
maskinstrikke__intr & butikken maskinstrikker &
masturbere__intr & de masturberer &
maule__intr & innbyggerne mauler &
medbestemme__intr & de ansattte medbestemmer &
meditere__intr & guruen mediterer &
medvirke__intr & myndighetene medvirker &
megle__intr & naboene megler &
mekle__intr & partene mekler &
mekre__intr & geitene mekrer &
mellomlande__intr & flyet mellomlander &
menstruere__intr & jentene menstruerer &
messe__intr & presten messer &
midle__intr & dommeren midler &
mige__intr & han miger &
migrere__intr & bøndene migrerer &
mildne__intr & været mildner &
mildnes__intr & sinnet mildnes med årene &
mime__intr & skuespillerne mimer &
mimre__intr & oldingene mimrer &
minere__intr & sprengningsmannskapene minerer &
minke__intr & pengereservene minker &
minskes__intr & avstandene minskes &
misjonere__intr & politikerne misjonerer &
mislykkes__intr & opprørerne mislykkes &
missnakke__intr & lederen missnakker &
mistrives__intr & deltagerne mistrives &
mjaue__intr & katten mjauer &
mjuklande__intr & flyet mjuklander &
mjukne__intr & stoffet mjukner &
modne__intr & plommene modner &
modnes__intr & plommene modnes &
modulere__intr & musikerne modulerer &
mompe__intr & guttene momper &
monne__intr & bidragene monner &
moppe__intr & vaskehjelpen mopper &
moralisere__intr & ledelsen moraliserer &
morkne__intr & plankene morkner &
morse__intr & telegrafisten morser &
mose__intr & maskinene moser &
mosjonere__intr & deltagerne mosjonerer &
motdemonstrere__intr & beboerne motdemonstrerer &
motspionere__intr & vi motspionerer &
mudre__intr & bunnen mudrer &
mugne__intr & syltetøyet mugner &
mukke__intr & de ansatte mukker &
mule__intr & mennene muler &
mulle__intr & mennene muller &
mulre__intr & mennene mulrer &
multitaske__intr & guttene multitasker &
mumle__intr & folket mumler &
munnhogges__intr & debattantene munnhogges &
munnhugges__intr & debattantene munnhugges &
mure__intr & firmaet murer &
murre__intr & folket murrer &
musisere__intr & musikerne musiserer &
mussere__intr & vinen musserer &
mute__intr & ørnen muter &
mutere__intr & viruset muterer &
mygle__intr & halmen mygler &
myklande__intr & flyet myklander &
mykne__intr & stoffet mykner &
myknes__intr & forholdet myknes &
myldre__intr & maurene myldrer &
myse__intr & deltagerne myser &
myte__intr & de innviede myter &
mørkne__intr & himmelen mørkner &
mørne__intr & skinkene mørner &
møtes__intr & demonstrantene møtes &
måpe__intr & tilskuerne måper &
nage__intr & tvilen nager &
nappe__intr & fisken napper &
naske__intr & uteliggerne nasker &
naube__intr & tiggerne nauber &
naue__intr & han nauer ikke &
navigere__intr & styrmannen navigerer &
nebbes__intr & rivalene nebbes &
nedarves__intr & genene nedarves &
nedkomme__intr & hun nedkommer &
neie__intr & jentene neier &
nekte__intr & ledelsen nekter &
nevehelse__intr & deltakerne nevehelser &
nevehilse__intr & deltakerne nevehilser &
nevetakes__intr & deltakerne nevetakes &
nikke__intr & deltakerne nikker &
nippe__intr & vinsmakerne nipper &
nisse__intr & gutten nisser &
nistirre__intr & deltakerne nistirrer &
nubbe__intr & kameratene nubber &
nudde__intr & skomakeren nudder &
nugge__intr & fisken nugger &
nuppe__intr & klærne nupper &
nuske__intr & sauene nusker &
nusle__intr & geitene nusler &
nusse__intr & kjærestene nusser &
nynne__intr & jentene nynner &
nype__intr & kona nyper &
nyse__intr & jenta nyser &
nytte__intr & initiativene nytter &
nyvåkne__intr & deltagerne nyvåkner &
nødlande__intr & flyet nødlander &
nøffe__intr & grisen nøffer &
nøle__intr & deltagerne nøler &
oie__intr & mannskapene oier &
okke__intr & kvinnene okker &
oksidere__intr & metallet oksiderer &
olme__intr & tilhørerne olmer &
omgåes__intr & kollegene omgåes &
omgås__intr & kollegene omgås &
omkomme__intr & flyktningene omkommer &
omprioritere__intr & politikerne omprioriterer &
omprosedere__intr & muskelen omprosederer &
omskifte__intr & været omskifter &
omstarte__intr & motoren omstarter &
onanere__intr & de onanerer &
onne__intr & bøndene onner &
operere__intr & kirurgene opererer &
opphøre__intr & ilden opphører &
opponere__intr & opposisjonen opponerer &
opprøres__intr & folk opprøres &
oppstå__intr & en uventet situasjon oppstår &
opptre__intr & skuespillerne opptrer &
oppvarte__intr & kelnerne oppvarter &
orge__intr & kameratene orger &
orkestrere__intr & dirigenten orkestrerer &
oscillere__intr & lyset oscillerer &
ose__intr & tranlampene oser &
otre__intr & firkerne otrer &
overdosere__intr & legene overdoserer &
overdrive__intr & journalistene overdriver &
overlappe__intr & sirklene overlapper &
overleve__intr & flyktningene overlever &
overmodnes__intr & problemstillingen overmodnes &
overnatte__intr & gjestene overnatter &
overopphetes__intr & havene overopphetes &
overraske__intr & deltagerne overrasker &
overreagere__intr & myndighetene overreagerer &
overspille__intr & spillerne overspiller &
overvintre__intr & gjestene overvintrer &
pace__intr & sekundantene pacer &
paffe__intr & skyterne paffer &
pakke__intr & gjestene pakker &
panorere__intr & kameraet panorerer &
paradere__intr & troppene paraderer &
paraglidere__intr & guttene paragliderer &
paraseile__intr & guttene paraseiler &
parasittere__intr & organismene parasitterer &
parkere__intr & bilene parkerer &
parlamentere__intr & politikerne parlamenterer &
parlere__intr & partene parlerer &
partisipere__intr & deltagerne partisiperer &
passe__intr & klærne passer &
passiare__intr & gjestene passiarer &
patruljere__intr & troppene patruljerer &
patte__intr & hvalene patter &
pausere__intr & orkesteret pauserer &
peke__intr & gutten peker &
perle__intr & svettedråpene perler &
perse__intr & løperne perser &
persistere__intr & misforholdet persisterer &
perspirere__intr & deltagerne perspirerer &
pese__intr & løperne peser &
phishe__intr & hackerne phisher &
pigge__intr & skiløperne pigger &
pigmentere__intr & huden pigmenterer &
pilke__intr & fiskerne pilker &
pimpe__intr & parvenyene pimper &
pinke__intr & gutten pinker &
pipe__intr & fuglungene piper &
piple__intr & dråpene pipler &
pippe__intr & fuglene pipper &
pirouettere__intr & skøyteløpersken pirouetterer &
piruettere__intr & skøyteløpersken piruetterer &
pisse__intr & de pisser &
pisspreike__intr & mellomlederen pisspreiker &
piste__intr & musene pister &
pistre__intr & kulene pistrer &
pjalle__intr & gutta pjaller &
pjatte__intr & representantene pjatter &
pjoltre__intr & kameratene pjoltrer &
pjutre__intr & kaffen pjutrer &
plane__intr & hjulene planer &
plapre__intr & konene plaprer &
plaske__intr & barna plasker &
plinge__intr & glassbitene plinger &
plire__intr & mannen plirer &
pludre__intr & barna pludrer &
plundre__intr & amatørene plundrer &
plyndre__intr & bandittene plyndrer &
plystre__intr & guttene plystrer &
pløse__intr & de pløser &
pokulere__intr & gjestene pokulerer &
polemisere__intr & redaktørene polemiserer &
polymerisere__intr & de polymeriserer &
poppe__intr & korkene popper &
posere__intr & skuespillerne poserer &
prakkes__intr & brukerne prakkes &
prale__intr & parvenyene praler & 
prange__intr & parvenyene pranger &
prasle__intr & løvbladene prasler &
prate__intr & naboene prater &
predike__intr & prosten prediker &
preke__intr & prosten preker &
preludere__intr & spillemannen preluderer &
prettes__intr & ungdommene prettes &
prime__intr & maleren primer &
proe__intr & kusken proer &
prognosere__intr & økonomene prognoserer &
prognostisere__intr & økonomene prognostiserer &
promenere__intr & turistene promenerer &
prompe__intr & kuene promper &
propagandere__intr & politikerne propaganderer &
protestere__intr & demonstrantene protesterer &
protte__intr & kusken protter &
proviantere__intr & deltagerne provianterer &
pruste__intr & hesten pruster &
prute__intr & selgerne pruter &
prøvebore__intr & oljeselskapene prøveborer &
prøvefilme__intr & filmselskapene prøvefilmer &
psykologisere__intr & legene psykologiserer &
ptroe__intr & kusken ptroer &
ptrotte__intr & kusken ptrotter &
puffe__intr & motspillerne puffer &
puge__intr & elevene puger &
pugge__intr & elevene pugger &
puldre__intr & vannet puldrer &
pule__intr & kjærestene puler &
pulse__intr & signalene pulser &
pulsere__intr & blodet pulserer &
pumpe__intr & maskinene pumper &
pumpebremse__intr & sjåføren pumpebremser &
punche__intr & dataassistenten puncher &
punktere__intr & dekket punkterer &
purke__intr & grisen purker &
purle__intr & bekken purler &
purre__intr & søkerne purrer &
pusle__intr & pensjonistene pusler &
puste__intr & deltagerne puster &
putle__intr & pensjonistene putler &
putre__intr & kjelen putrer &
pæle__intr & arbeiderne pæler &
pøble__intr & pøblene pøbler &
pøse__intr & regnet pøser &
pågå__intr & kampene pågår &
påløpe__intr & utgiftene påløper &
rable__intr & ungene rabler &
radiere__intr & strålene radierer &
rafte__intr & turistene rafter &
rake__intr & gartneren raker &
rakne__intr & tråden rakner &
raljere__intr & kritikerne raljerer &
ralle__intr & den døende raller &
rangle__intr & gjestene rangler &
rape__intr & gutten raper &
rappe__intr & gjengene rapper &
rapse__intr & guttene rapser &
rase__intr & deltagerne raser &
rasle__intr & løvet rasler &
raste__intr & turistene raster &
ratle__intr & løvet ratler &
ratte__intr & bilførerne ratter &
rause__intr & stenblokkene rauser &
raute__intr & kuene rauter &
reagere__intr & deltagerne reagerer &
rebellere__intr & opprørerne rebellerer &
redde__intr & redningsmannskapene redder &
rede__intr & rederne reder &
redoble__intr & tapene redobler &
reduseres__intr & isbreene reduseres &
regenerere__intr & cellene regenererer &
regjere__intr & kongen regjerer &
regne__intr & elevene regner &
reike__intr & de reiker omkring &
reinvestere__intr & investorene reinvesterer &
reklamere__intr & firmaet reklamerer &
rekne__intr & elevene rekner &
rekoagulere__intr & blodet rekoagulerer &
rekognosere__intr & speiderne rekognoserer &
rekreere__intr & pasienttene rekreerer &
reminisere__intr & veteranene reminiserer &
remisere__intr & spillerne remiserer &
remje__intr & reporteren remjer &
replisere__intr & debattantene repliserer &
residivere__intr & sykdommen residiverer &
resignere__intr & deltagerne resignerer &
resistere__intr & forsvarerne resisterer &
resonnere__intr & deltagerne resonnerer &
respirere__intr & pasienten respirerer &
respondere__intr & deltagerne responderer &
restarte__intr & programmet restarter &
restere__intr & skatten resterer &
retardere__intr & utviklingen retarderer &
reversere__intr & motoren reverserer &
revne__intr & seilduken revner &
revoltere__intr & de ansatte revolterer &
ri__intr & rytterne rir &
ride__intr & rytterne rider &
rikosjettere__intr & kulene rikosjetterer &
rikse__intr & gresshoppen rikser &
rikte__intr & stolen rikter &
rime__intr & marken rimer &
rine__intr & hesten riner &
ringe__intr & deltagerne ringer &
ringle__intr & bjellene ringler &
rinne__intr & floden rinner &
ripostere__intr & debattantene riposterer &
risle__intr & bekken risler &
riste__intr & huset rister &
rite__intr & trollmennene riter &
rivalisere__intr & rivalene rivaliserer &
rocke__intr & ungdommene rocker &
rokere__intr & sjakkspilleren rokerer &
rokke__intr & skikkelsen rokker &
rolle__intr & danserne roller &
romstere__intr & tyvene romsterer &
rope__intr & kapteinen roper &
rote__intr & deltagerne roter &
ruge__intr & fuglene ruger &
ruges__intr & eggene ruges &
rugge__intr & stolen rugger &
rugle__intr & vognen rugler &
rullere__intr & vervene rullerer &
rulte__intr & karene rulter &
ruminere__intr & vismennene ruminerer &
rumle__intr & maven rumler &
rune__intr & trollmannen runer &
runge__intr & ropene runger &
runke__intr & gutten runker &
rushe__intr & laget rusher &
ruste-1__intr & stormaktene ruster &
ruste-2__intr & rørene ruster &
rustne__intr & motordelene rustner &
ruve__intr & byggene ruver &
ry__intr & skinnfellen ryr &
rydde__intr & foreldrene rydder &
rygge__intr & bilen rygger &
ryggsvømme__intr & barna ryggsvømmer &
ryke__intr & tauet ryker &
ryktes__intr & slagsmålet ryktes &
ryte__intr & bjørnen ryter &
røde__intr & gubbene røder &
rødme__intr & gutten rødmer &
rødne__intr & høstløvet rødner &
røke__intr & gubbene røker &
røle__intr & fyllikene røler &
rømme__intr & fangene rømmer &
røyke__intr & gubbene røyker &
røyte__intr & katten røyter &
rå__intr & skjebnen rår &
råde__intr & skjebnen råder &
rådlegge__intr & generalene rådlegger &
rådslå__intr & generalene rådslår &
råkjøre__intr & guttene råkjører &
råle__intr & guttene råler &
råne__intr & bilene råner &
råtne__intr & eplene råtner &
sabbe__intr & gubbene sabber &
safe__intr & deltagerne safer &
safte__intr & bonden safter &
sage__intr & bonden sager &
sakke__intr & føttene sakker &
sakse__intr & hopperen sakser &
saktne__intr & toget saktner &
salivere__intr & pasienten saliverer &
salutere__intr & soldatene saluterer &
saluttere__intr & soldatene salutterer &
samarbeide__intr & partene samarbeider &
sameksistere__intr & folkegruppene sameksisterer &
samles__intr & tilhengerne samles &
sammenstøte__intr & vognene sammenstøter &
samstave__intr & tekstene samstaver &
samstemme__intr & tekstene samstemmer &
samsvare__intr & tekstene samsvarer &
samtale__intr & partene samtaler &
samvirke__intr & partene samvirker &
sangre__intr & klokken sangrer &
satirisere__intr & artiklene satiriserer &
satse__intr & bankene satser &
sause__intr & tobakken sauser &
savle__intr & gubbene savler &
score__intr & laget scorer &
sees__intr & naboene sees &
segne__intr & helten segner &
seinke__intr & forholdene seinker &
seire__intr & naboklubben seirer &
sekundere__intr & sekundanten sekunderer &
semaforere__intr & sjøfolkene semaforerer &
serve__intr & spilleren server &
servere__intr & kokkene serverer &
ses__intr & vennene ses &
sesongdebutere__intr & lagene sesongdebuterer &
setre__intr & budeia setrer &
sexdebutere__intr & ungdommene sexdebuterer &
shake__intr & danserne shaker &
shoppe__intr & turistene shopper &
showe__intr & deltagerne shower &
sidrikke__intr & gubbene sidrikker &
sige__intr & buksa siger &
signe__intr & presten signer &
signere__intr & sorenskriveren signerer &
sike__intr & saften siker &
sikksakke__intr & løperne sikksakker &
sikle__intr & gubbene sikler &
silblø__intr & fangene silblør &
sildre__intr & bekkene sildrer &
sile__intr & svetten siler &
silrenne__intr & tårene silrenner &
single__intr & glassbitene singler &
sinke__intr & snekkeren sinker &
sipe__intr & deregnet siper &
sippe__intr & regnet sipper &
sirkle__intr & kråkene sirkler &
sirkulere__intr & ryktene sirkulerer &
sitre__intr & bena sitrer &
sitte__intr & deltagerne sitter &
sjangle__intr & sjøfolkene sjangler &
sjanse__intr & guttene sjanser &
sjaske__intr & sjuskene sjasker &
sjaue__intr & arbeiderne sjauer &
sjefe__intr & lederne sjefer &
sjeide__intr & gruvearbeiderne sjeider &
sjekke__intr & politiet sjekker &
sjevre__intr & skrikene sjevrer &
sjofle__intr & ledelsen sjofler &
sjoge__intr & elven sjoger &
sjogse__intr & elven sjogser &
sjokke__intr & joggerne sjokker &
sjokkåpne__intr & laget sjokkåpner &
sjonglere__intr & sjonglørene sjonglerer &
sjukne__intr & håpet sjukner &
sjuske__intr & sjuskene sjusker &
skaffe__intr & sjøfolkene skaffer &
skake__intr & stillaset skaker &
skalle__intr & spillerne skaller &
skalte__intr & de skalter og valter &
skamfryse__intr & hyttebeboerne skamfryser &
skandere__intr & oppleseren skanderer &
skare__intr & snøen skarer &
skarre__intr & bergenserne skarrer &
skeie__intr & bilen skeier &
skeine__intr & fuglene skeiner &
skeise__intr & barna skeiser &
skeivle__intr & fuglene skeivler &
skifte__intr & motene skifter &
skilles__intr & partene skilles &
skimle__intr & osten skimler &
skimre__intr & bildene skimrer &
skingre__intr & stemmen skingrer &
skinne__intr & solen skinner &
skite__intr & gardsguten skiter &
skjele__intr & eleven skjeler &
skjelle__intr & torgkonene skjeller &
skjelme__intr & erteplanten skjelmer &
skjelve__intr & de skyldige skjelver &
skjemmes__intr & de skyldige skjemmes &
skjemte__intr & jentene skjemter &
skjene__intr & vogna skjener &
skjenne__intr & nabokona skjenner &
skjerpe__intr & gullgraverne skjerper &
skjærne__intr & kornet skjærner &
skjørne__intr & seilet skjørner &
skli__intr & ungene sklir &
skofte__intr & leiearbeiderne skofter &
skoggerle__intr & tilskuerne skoggerler &
skogre__intr & orrfuglen skogrer &
skole__intr & kommunen skoler &
skotte__intr & rottene skotter &
skralle__intr & tordenen skraller &
skramle__intr & metallbitene skramler &
skrangle__intr & vogna skrangler &
skrante__intr & pasienten skranter &
skratte__intr & tilskuerne skratter &
skrattle__intr & tilskuerne skrattler &
skravle__intr & naboene skravler &
skredderere__intr & nissene skreddererer &
skrelle__intr & tordenen skreller &
skrense__intr & bussen skrenser &
skreve__intr & gymnastene skrever &
skrible__intr & skriverne skribler &
skrifte__intr & direktøren skrifter &
skrike__intr & tilskuerne skriker &
skrive__intr & forfattere skriver &
skru__intr & han skrur &
skrue__intr & snekkeren skruer &
skrumme__intr & hackerne skrummer &
skrumpe__intr & beholdningen skrumper &
skruve__intr & snekkeren skruver &
skryte__intr & vinnerne skryter &
skrø__intr & pasienten skrør &
skrøfte__intr & direktøren skrøfter &
skrømte__intr & spøkelsene skrømter &
skrøne__intr & elevene skrøner &
skrå__intr & linjen skrår &
skråle__intr & tilskuerne skråler &
skråne__intr & bakken skråner &
skuffe__intr & deltagerne skuffer &
skule__intr & de fremmøtte skuler &
skulse__intr & partene skulser &
skumle__intr & deltagerne skumler &
skumlese__intr & kritikerne skumleser &
skumme__intr & ølet skummer &
skumpe__intr & vogna skumper &
skumple__intr & vogna skumpler &
skumtygge__intr & msnnen skumtygger &
skurre__intr & radioen skurrer &
skvadronere__intr & storbonden skvadronerer &
skvaldre__intr & selgerne skvaldrer &
skvale__intr & vannet skvaler &
skvalpe__intr & bølgene skvalper &
skvatre__intr & spurvene skvatrer &
skvette__intr & vannet skvetter &
skvulpe__intr & bølgene skvulper &
skyggebokse__intr & brødrene skyggebokser &
skøye__intr & deltagerne skøyer &
skøyte__intr & jentene skøyter &
skåle__intr & vinnerne skåler &
skåre__intr & laget skårer &
skåte__intr & roeren skåter &
slabbe__intr & ungene slabber &
sladde__intr & bilen sladder &
sladre__intr & nabokonene sladrer &
slafse__intr & ungene slafser &
slagge__intr & kullet slagger &
slakne__intr & repene slakner &
slakte__intr & bøndene slakter &
slamme__intr & murerne slammer &
slampe__intr & guttene slamper &
slamre__intr & dørene slamrer &
slamse__intr & kua slamser &
slapne__intr & stemningen slapner &
slarke__intr & håndverkerne slarker &
slarve__intr & deltagerne slarver &
slaske__intr & seilet slasker &
slave__intr & fangene slaver &
slegge__intr & smeden slegger &
sleive__intr & skiene sleiver &
slenge__intr & tauendene slenger &
sleske__intr & intrigantene slesker &
sletne__intr & rynkene sletner &
sleve__intr & pasienten slever &
slime__intr & fiskeskinnet slimer &
slingre__intr & vogna slingrer &
sliske__intr & intrigantene slisker &
slisse__intr & snekkeren slisser &
slite__intr & krigsveteranene sliter &
slitne__intr & tauet slitner &
slokne__intr & brannen slokner &
slubbe__intr & dagdriverne slubber &
slubre__intr & dagdriverne slubrer &
sludre__intr & naboene sludrer &
slufse__intr & gutten slufser &
slukne__intr & ilden slukner &
slumre__intr & kjempene slumrer &
slumse__intr & guttene slumser &
sluntre__intr & dagdriverne sluntrer &
slure__intr & ankeret slurer &
slurke__intr & trollene slurker &
slurpe__intr & guttene slurper &
slurve__intr & elevene slurver &
sluske__intr & skribenten slusker &
slutte__intr & direktørene slutter &
sløre__intr & seilbaåten slører &
sløse__intr & husholdningene sløser &
sløve__intr & dagdriverne sløver &
sløvne__intr & konsentrasjonen sløvner &
sløyde__intr & elevene sløyder &
slå__intr & politifolkene slår &
slåss__intr & konkurrentene slåss &
smake__intr & suppen smaker &
smalne__intr & stien smalner &
smaske__intr & trollet smasker &
smatre__intr & mitraljøsene smatrer &
smatte__intr & gubbene smatter &
smekke__intr & dørlåsen smekker &
smelle__intr & dørene smeller &
smelte__intr & isen smelter &
smerte__intr & nyheten smerter &
smi__intr & smeden smir &
smigre__intr & påskjønnelsen smigrer &
smile__intr & deltagerne smiler &
smiske__intr & intrigantene smisker &
smitte__intr & ebola smitter &
smulne__intr & brødet smulner &
småkoke__intr & potetene småkoker &
småløpe__intr & joggerne småløper &
småprate__intr & deltagerne småprater &
småspise__intr & musene småspiser &
snadre__intr & endene snadrer &
snakke__intr & deltagerne snakker &
snapse__intr & gubbene snapser &
snaske__intr & grisene snasker &
snavle__intr & gubbene snavler &
sne__intr & asken sner &
snekkerere__intr & deltagerne snekkererer &
snekre__intr & deltagerne snekrer &
snerpe__intr & lukten snerper &
snerre__intr & tigeren snerrer &
sniffe__intr & snifferne sniffer &
snobbe__intr & deltagerne snobber &
snoke__intr & deltagerne snoker &
snope__intr & deltagerne snoper &
snorke__intr & deltagerne snorker &
snorkle__intr & svømmerne snorkler &
snorksove__intr & deltagerne snorksover &
snu__intr & deltagerne snur &
snubbe__intr & menneskene snubber &
snuble__intr & deltagerne snubler &
snufse__intr & deltagerne snufser &
snuse__intr & gubbene snuser &
snuske__intr & opportunistene snusker &
snylte__intr & opportunistene snylter &
snø__intr & asken snør &
snøfle__intr & opportunistene snøfler &
snøfte__intr & grisen snøfter &
snørekjøre__intr & deltagerne snørekjører &
snøse__intr & fiskeren snøser &
snøvle__intr & gubbene snøvler &
snåle__intr & pantelåneren snåler &
snåve__intr & gubnen snåver &
sodomisere__intr & synderne sodomiserer &
sollisitere__intr & søkerne sollisiterer &
solmisere__intr & sangerne solmiserer &
somle__intr & deltagerne somler &
sope__intr & gatefeierne soper &
soppe__intr & tømmerfløterne sopper &
sordinere__intr & musikerne sordinerer &
sose__intr & deltagerne soser &
sote__intr & lokomotivene soter &
sove__intr & deltagerne sover &
sovne__intr & deltagerne sovner &
spa__intr & deltagerne spar &
spakne__intr & protestene spakner &
spandere__intr & deltagerne spanderer &
spane__intr & politiet spaner &
spanke__intr & konsulen spanker &
spankulere__intr & konsulen spankulerer &
spare__intr & deltagerne sparer &
sparke__intr & babyen sparker &
sparre__intr & bokserne sparrer &
spase__intr & malerne spaser &
speede__intr & deltagerne speeder &
speide__intr & deltagerne speider &
spekse__intr & gjøglerne spekser &
spekulere__intr & spekulantene spekulerer &
spenne__intr & hesten spenner &
spikke__intr & speiderne spikker &
spikre__intr & snekkeren spikrer &
spille__intr & deltagerne spiller &
spinke__intr & sparerne spinker &
spinne__intr & nornene spinner &
spionere__intr & naboene spionerer &
spire__intr & blomstene spirer &
spise__intr & herskapet spiser &
sporte__intr & adelen sporter &
sprade__intr & adelen sprader &
spragle__intr & farvene spragler &
sprake__intr & kvistene spraker &
sprekke__intr & glasset sprekker &
sprelle__intr & fiskene spreller &
sprengkjøre__intr & deltagerne sprengkjører &
sprenglese__intr & elevene sprengleser &
sprike__intr & grenene spriker &
springe__intr & ungene springer &
sprinte__intr & løperne sprinter &
sprudle__intr & champagnen sprudler &
sprute__intr & geysiren spruter &
spurte__intr & deltagerne spurter &
spy__intr & deltagerne spyr &
spytte__intr & pasienten spytter &
spøke__intr & deltagerne spøker &
spørre__intr & quizlederen spør &
spørres__intr & nyheten spørres &
spå__intr & spåkonen spår &
stabbe__intr & ungene stabber &
stagnere__intr & veksten stagnerer &
stamme__intr & pasienten stammer &
stampe__intr & oksene stamper &
stane__intr & hesten staner &
stange__intr & oksene stanger &
stanke__intr & fiskelikene stanker &
stanse-1__intr & kortesjeb stanser &
starte__intr & deltagerne starter &
stave__intr & elevene staver &
steike__intr & sola steiker &
steile__intr & hesten steiler &
steke__intr & sola steker &
stele__intr & kjeltringene steler &
stemme__intr & målingene stemmer &
stenge__intr & butikken stenger &
steppe__intr & danseren stepper &
sterkne__intr & vindsuset sterkner &
steve__intr & bestemoren stever &
stevje__intr & bestemoren stevjer &
stikke__intr & tornene stikker &
stikle__intr & ytringene stikler &
stilne__intr & vinden stilner &
stime__intr & fisken stimer &
stinke__intr & fisken stinker &
stirre__intr & tilskuerne stirrer &
stivfryse__intr & deltagerne stivfryser &
stivne__intr & skorpen stivner &
stjele__intr & agentene stjeler &
stjernekikke__intr & astronomen stjernekikker &
stoppe__intr & maskinene stopper &
storle__intr & tilhørerne storler &
stormgjø__intr & hunden stormgjør &
storskrike__intr & barnet storskriker &
storspille__intr & laget storspiller &
stortrives__intr & spillerne stortrives &
stotre__intr & de anklagede stotrer &
straffeforfølge__intr & myndighetene straffeforfølger &
stramme__intr & klærne strammer &
strammes__intr & båndene strammes &
strande__intr & båten strander &
strante__intr & trekronene stranter &
streake__intr & tilskueren streaker &
streame__intr & tilhengerne streamer &
streike__intr & arbeiderne streiker &
stresse__intr & deltagerne stresser &
streve__intr & deltagerne strever &
stri__intr & deltagerne strir &
stride__intr & ridderne strider &
strides__intr & deltagerne strides &
stridgråte__intr & deltagerne stridgråter &
strigråte__intr & deltagerne strigråter &
strikke__intr & de strikker &
strippe__intr & jentene stripper &
stritte__intr & motstanderne stritter &
strutte__intr & kjolene strutter &
stråle__intr & lysene stråler &
studere__intr & studentene studerer &
stulle__intr & mormor stuller &
stunde__intr & sjelen stunder &
stupbombe__intr & flyet stupbomber &
stupe__intr & aksjekursene stuper &
sture__intr & taperne sturer &
sturte__intr & fuglen sturter &
stusse__intr & deltagerne stusser &
stutne__intr & dagene stutner &
stygges__intr & tilskuerne stygges &
styltre__intr & guttene styltrer &
styre__intr & sjåføren styrer &
styrkes__intr & vennskapet styrkes &
styrtblø__intr & de sårede styrtblør &
styrte__intr & flyet styrter &
stø__intr & støttebandasjen stør &
støe__intr & støttebandasjen støer &
støkke__intr & kona støkker &
støle__intr & kyrne støler &
stølne__intr & musklene stølner &
stønne__intr & slavene stønner &
størkne__intr & sementen størkner &
støve__intr & bilene støver &
støvsuge__intr & gutten støvsuger &
støye__intr & guttene støyer &
stå__intr & monumentet står &
ståke__intr & ungene ståker &
subbe__intr & buksene subber &
subtrahere__intr & eleven subtraherer &
sufflere__intr & suffløsen sufflerer &
suge__intr & filmen suger &
sukke__intr & piken sukker &
sukle__intr & vannet sukler &
sulke__intr & bølgene sulker &
sulle__intr & byråkratene suller &
sulte__intr & innbyggerne sulter &
summe__intr & biene summer &
supe__intr & naboen super &
supere__intr & herskapet superer &
surfe__intr & badegjestene surfer &
surkle__intr & støvlene surkler &
surle__intr & bekken surler &
surmule__intr & taperne surmuler &
surne__intr & vennskapet surner &
surre__intr & myggene surrer &
susle__intr & vannet susler &
susse__intr & kjærestene susser &
sutre__intr & deltagerne sutrer &
svage__intr & treet svager &
svaie__intr & treet svaier &
svalne__intr & vinden svalner &
svanse__intr & rottene svanser &
svare__intr & sannheten svarer &
svartne__intr & horisonten svartner &
svarve__intr & stangen svarver &
sveise__intr & rørleggeren sveiser &
svelge__intr & fangen svelger &
svelgje__intr & fangen svelgjer &
svelle__intr & ertene sveller &
svelte__intr & fangene svelter &
sverge__intr & vitnene sverger &
sverje__intr & vitnene sverjer &
sverme__intr & myggene svermer &
svette__intr & deltagerne svetter &
sveve__intr & ballongene svever &
svi__intr & hodebunnen svir &
svikte__intr & bjelkene svikter &
svimle__intr & farten svimler &
svimre__intr & farten svimrer &
svinse__intr & rottene svinser &
svire__intr & svirebrødrene svirer &
svirre__intr & ryktene svirrer &
svis__intr & avlingene svis &
svive__intr & møllehjulet sviver &
svulme__intr & ankelen svulmer &
svulne__intr & ankelen svulner &
swinge__intr & jubilantene swinger &
sy__intr & syerskene syr &
syde__intr & vannet syder &
sykle__intr & mosjonistene sykler &
sykne__intr & plantene sykner &
sylte__intr & bøndene sylter &
sympatistreike__intr & dltagernee sympatistreiker &
synde__intr & tollerne synder &
syne__intr & pokerspilleren syner &
synge__intr & kirkesangerne synger &
synse__intr & deltagerne synser &
syrne__intr & vinen syrner &
syte__intr & taperne syter &
sætre__intr & budeia sætrer &
søke__intr & hackerne søker &
søkke__intr & loddet søkker &
søle__intr & barna søler &
sømme-2__intr & verkstedet sømmer &
sørge__intr & familien sørger &
så__intr & bonden sår &
tagne__intr & nattergalen tagner &
takke__intr & deltagerne takker &
takse__intr & flyet takser &
taktere__intr & dirigenten takterer &
tale__intr & demagogene taler &
tamse__intr & hesten tamser &
tane__intr & hesten taner &
tanke__intr & båten tanker &
tape__intr & laget taper &
tappdanse__intr & danserne tappdanser &
tasle__intr & nissene tasler &
tasse__intr & nissen tasser &
taxe__intr & flyet taxer &
tegne__intr & arkitekten tegner &
tele__intr & stien teler &
telekommunikere__intr & partene telekommunikerer &
teleksere__intr & partene telekserer &
telle__intr & resultatene teller &
telte__intr & turistene telter &
tenke__intr & filosofene tenker &
tetne__intr & rørene tetner &
teve__intr & fylliken tever &
tevle__intr & nabobygdene tevler &
tie__intr & vitnene tier &
tigge__intr & nabobygdene tigger &
tikke__intr & klokka tikker &
tilfryse__intr & sjøene tilfryser &
tilfyke__intr & vidda tilfyker &
tilgro__intr & tunene tilgror &
tilta__intr & opptøyene tiltar &
tindre__intr & stjernene tindrer &
tine__intr & isbreene tiner &
tinkle__intr & klokkene tinkler &
tiple__intr & tårene tipler &
tippe__intr & vognen tipper &
tiske__intr & naboene tisker &
tisle__intr & barna tisler &
tisse__intr & barna tisser &
tjadre__intr & fuglene tjadrer &
tjatre__intr & fuglene tjatrer &
tjatte__intr & guttene tjatter &
tjelde__intr & kongshæren tjelder &
tjenestegjøre__intr & soldatene tjenestegjør &
tjenstgjøre__intr & soldatene tjenstgjør &
tjone__intr & smeden tjoner &
tjukne__intr & tåka tjukner &
tjuve__intr & tyvene tjuver &
tjuvlytte__intr & naboene tjuvlytter &
tjuvstarte__intr & løperen tjuvstarter &
tjuvtitte__intr & naboene tjuvtitter &
tjuvtrene__intr & spillerne tjuvtrener &
tjåke__intr & ungdommene tjåker &
tomse__intr & ungene tomser &
tordne__intr & kritikerne tordner &
torve__intr & bøndene torver &
trabelere__intr & folk trabelerer &
trafficke__intr & de kriminelle trafficker &
trakke__intr & beboerne trakker &
tralle__intr & kona traller &
trampe__intr & tilskuerne tramper &
transmigrere__intr & krigsofre transmigrerer &
transmutere__intr & mutantene transmuterer &
transpirere__intr & deltagerne transpirerer &
traske__intr & flyktningene trasker &
trasse__intr & småbarn trasser &
trave__intr & hestene traver &
traversere__intr & klatrerne traverserer &
treffes__intr & vennene treffes &
trelle__intr & slavene treller &
tremulere__intr & sangerinnen tremulerer &
trene__intr & deltagerne trener &
trenges__intr & hjelpen trenges &
trengs__intr & hjelpen trengs &
tretne__intr & deltagerne tretner &
trette__intr & partnerne tretter &
trikke__intr & deltagerne trikker &
trikse__intr & politikerne trikser &
trille__intr & vogna triller &
trimme__intr & deltagerne trimmer &
trine__intr & fruene triner &
trinse__intr & bøttene trinser &
trippe__intr & hønene tripper &
triumfere__intr & naboene triumferer &
trives__intr & deltagerne trives &
tro__intr & de troende tror &
trolle__intr & magikerne troller &
tromme__intr & deltagerne trommer &
trone__intr & kongen troner &
tru__intr & de truende trur &
trumfe__intr & direktøren trumfer &
trutne__intr & båten trutner &
trygle__intr & innbyggerne trygler &
trylle__intr & tryllekunstneren tryller &
tryne__intr & laget tryner &
tryte__intr & fossen tryter &
trø__intr & vandalene trør &
trøstespise__intr & deltagerne trøstespiser &
trøtne__intr & deltagerne trøtner &
trå__intr & deltagerne trår &
tråkke__intr & ryddemannskapene tråkker &
tråkle__intr & jentene tråkler &
tråle__intr & fiskebåten tråler &
tråve__intr & hesten tråver &
tulle__intr & jentene tuller &
ture__intr & fossen turer &
turne__intr & atletene turner &
turnere__intr & bandet turnerer &
tusje__intr & tegneren tusjer &
tusle__intr & nissene tusler &
tusse__intr & nissene tusser &
tute__intr & bilene tuter &
tutle__intr & husmannen tutler &
tverrsnu__intr & mennene tverrsnur &
tverrstanse__intr & bussen tverrstanser &
tverrvende__intr & spilleren tverrvender &
tvile__intr & filosofen tviler &
tvistes__intr & naboene tvistes &
twiste__intr & gjestene twister &
tygge__intr & musa tygger &
tykne__intr & vellingen tykner &
tynge__intr & bekymringene tynger &
tyste__intr & kameratene tyster &
tystne__intr & tilhørerne tystner &
tyte__intr & pastaen tyter &
tyvlytte__intr & demonstrantene tyvlytter &
tyvstarte__intr & sprinteren tyvstarter &
tyvtitte__intr & barna tyvtitter &
tyvtrene__intr & spillerne tyvtrener &
tære__intr & bekymringene tærer &
tæres__intr & tilliten tæres &
tø__intr & islaget tør &
tøffe__intr & båten tøffer &
tømre__intr & tømrerne tømrer &
tørke__intr & klærne tørker &
tørrkoke__intr & kaserollen tørrkoker &
tørrtrene__intr & skigutta tørrtrener &
tørste__intr & befolkningen tørster &
tøve__intr & guttene tøver &
tøyse__intr & guttene tøyser &
tårast__intr & ofrene tårast &
ule__intr & ulvene uler &
ulke__intr & pasienten ulker &
ulme__intr & glørne ulmer &
underby__intr & selgerne underbyr &
underdrive__intr & ledelsen underdriver &
undergjære__intr & ølet undergjærer &
underhandle__intr & partene underhandler &
underkommunisere__intr & ledelsen underkommuniserer &
underprestere__intr & laget underpresterer &
underspille__intr & skuespilleren underspiller &
undervise__intr & lærerne underviser &
undres__intr & filosofene undres &
unngjelde__intr & deltagerne unngjelder &
unnsleppe__intr & tyvene unnslepper &
unnslippe__intr & tyvene unnslipper &
urinere__intr & urinnvånerne urinerer &
utagere__intr & ledelsen utagerer &
utarte__intr & opptøyene utarter &
utbryte__intr & epidemien utbryter &
utdø__intr & stammene utdør &
utebli__intr & deltagerne uteblir &
utgå__intr & fristen utgår &
utkomme__intr & avisene utkommer &
utligne__intr & laget utligner &
utlikne__intr & laget utlikner &
uttvære__intr & fortelleren uttværer &
utvandre__intr & bøndene utvandrer &
utvaskes__intr & hulene utvaskes &
utvides__intr & bresprekkene utvides & 
utånde__intr & presidenten utånder &
vadre__intr & folk vadrer &
vagabondere__intr & tiggerne vagabonderer &
vagge__intr & statuen vagger &
vagle__intr & hønsene vagler &
vaie__intr & flagget vaier &
vake__intr & slektningene vaker &
vakne__intr & deltagerne vakner &
valne__intr & fingrene valner &
valpe__intr & hunden valper &
valse__intr & gjestene valser &
valte__intr & ledelsen valter &
vandle__intr & hanseatene vandler &
vansmekte__intr & fangene vansmekter &
vanstelle__intr & bonden vansteller &
vanstyre__intr & kongen vanstyrer &
vantrives__intr & vaktene vantrives &
variere__intr & prestasjonene varierer &
varmheve__intr & bakerne varmhever &
varpe__intr & mannskapet varper &
varsle__intr & tilskuerne varsler &
vaske__intr & renholderne vasker &
vedbli__intr & tilstanden vedblir &
vedde__intr & spillerne vedder &
vedvare__intr & regnet vedvarer &
vegetere__intr & herren vegeterer &
veide__intr & jegerne veider &
veie__intr & kiloene veier &
veikne__intr & knærne veikner &
veite__intr & bøndene veiter &
veive__intr & lysstrålen veiver &
vekne__intr & armene vekner &
velte__intr & vogna velter &
vemmes__intr & sambygdingene vemmes &
vente__intr & deltagerne venter &
verke__intr & tannen verker &
verpe__intr & hønene verper &
versere__intr & ryktene verserer &
versne__intr & situasjonen versner &
veve__intr & veverskene vever &
vibrere__intr & tonen vibrerer &
vifte__intr & tilhengerne vifter &
vigilere__intr & borgerne vigilerer &
vikariere__intr & legene vikarierer &
vildre__intr & dyrene vildrer &
vimre__intr & gjestene vimrer &
vimse__intr & gjestene vimser &
vinge__intr & fuglen vinger &
vingle__intr & ledelsen vingler &
vinke__intr & deltagerne vinker &
vinne__intr & laget vinner &
virke__intr & medisinen virker &
visle__intr & slangen visler &
visne__intr & plantene visner &
vite__intr & ekspertene vet &
vitne__intr & vitnene vitner &
vitse__intr & deltagerne vitser &
vivisekere__intr & laborantene vivisekerer &
voffe__intr & hunden voffer &
vogge__intr & båten vogger &
voltere__intr & fekteren volterer &
voltigere__intr & rytterne voltigerer &
vomere__intr & fylliken vomerer &
votere__intr & forsamlingen voterer &
vralte__intr & gassen vralter &
vredes__intr & gudene vredes &
vrimle__intr & menneskene vrimler &
vrinske__intr & hestene vrinsker &
vræle__intr & ungen vræler &
vrøvle__intr & fyllikene vrøvler &
vugge__intr & båten vugger &
væske__intr & såret væsker &
vøle__intr & beboerne vøler &
våke__intr & foreldrene våker &
våkne__intr & deltagerne våkner &
våle__intr & gutten våler &
våse__intr & fyllikene våser &
våtne__intr & underlaget våtner &
xerografere__intr & sekretæren xerograferer &
xylografere__intr & kunstneren xylograferer &
ydde__intr & plantene ydder &
yle__intr & snøfokket yler &
ynges__intr & utseendet ynges &
yngle__intr & fiskene yngler &
yre__intr & fiskene yrer &
yste__intr & budeia yster &
æresforplikte__intr & avtalen æresforplikter &
ødsle__intr & adelen ødsler &
øke__intr & vinden øker &
økonomisere__intr & husholdningene økonomiserer &
ønsketenke__intr & ledelsen ønsketenker &
øre__intr & mannskapet ører &
ørske__intr & fylliken ørsker &
ørte__intr & kua ørter &
øve__intr & danserne øver &
åpne__intr & butikken åpner &
