gni__trObl-obRefl-oblPRTOFob & hun gnir seg i nakken &
gnu__trObl-obRefl-oblPRTOFob & hun gnur seg i nakken &
hogge__trObl-obRefl-oblPRTOFob & hun hogger seg i foten &
holde__trObl-obRefl-oblPRTOFob & hun holder seg for nesen &
hugge__trObl-obRefl-oblPRTOFob & hun hugger seg i foten &
kile__trObl-obRefl-oblPRTOFob & hun kiler seg på nesen &
klabbe__trObl-obRefl-oblPRTOFob & han klabber seg i ansiktet &
klore__trObl-obRefl-oblPRTOFob & han klorer seg i nakken &
klø__trObl-obRefl-oblPRTOFob & hun klør seg i nakken &
knipe__trObl-obRefl-oblPRTOFob & hun kniper seg i armen &
kutte__trObl-obRefl-oblPRTOFob & han kutter seg i fingeren &
pille__trObl-obRefl-oblPRTOFob & han piller seg i nesen &
pirke__trObl-obRefl-oblPRTOFob & han pirker seg i hodebunnen &
skjære__trObl-obRefl-oblPRTOFob & hun skjærer seg i fingeren &
skrubbe__trObl-obRefl-oblPRTOFob & de skrubber seg i nakken &
skyte__trObl-obRefl-oblPRTOFob & hun skyter seg i nakken &
sleike__trObl-obRefl-oblPRTOFob & katten sleiker seg rundt munnen &
slenge-etter__trObl-obRefl-oblPRTOFob & apekattene slenger seg etter armene &
slikke__trObl-obRefl-oblPRTOFob & katten slikker seg i ansiktet &
slå__trObl-obRefl-oblPRTOFob & hun slår seg i hodet &
sminke__trObl-obRefl-oblPRTOFob & hun sminker seg rundt øynene &
stryke__trObl-obRefl-oblPRTOFob & hun stryker seg i ansiktet &
sverte__trObl-obRefl-oblPRTOFob & han sverter seg i ansiktet &
ta__trObl-obRefl-oblPRTOFob & hun tar seg i nakken &
tørke__trObl-obRefl-oblPRTOFob & hun tørker seg i ansiktet &
vaske__trObl-obRefl-oblPRTOFob & barna vasker seg i ansiktet &
