alboge__trPath-obRefl-obDir & hun alboger seg fram &
albue__trPath-obRefl-obDir & hun albuer seg frem &
bakse__trPath-obRefl-obDir & hun bakser seg frem &
bane__trPath-obRefl-obDir & hun baner seg frem &
baute__trPath-obRefl-obDir & hun bauter seg mot kaia &
begi__trPath-obRefl-obDir & hun begir seg ut &
bore__trPath-obRefl-obDir & tunnelarbeiderne borer seg frem &
braute__trPath-obRefl-obDir & festdeltagerne brauter seg frem &
brøyte__trPath-obRefl-obDir & hun brøyter seg frem &
buksere__trPath-obRefl-obDir & båten bukserer seg frem &
bukte__trPath-obRefl-obDir & hun bukter seg frem &
driste__trPath-obRefl-obDir & hun drister seg frem &
drømme__trPath-obRefl-obDir & hun drømmer seg bort &
eksperimentere__trPath-obRefl-obDir & hun eksperimenterer seg frem &
famle__trPath-obRefl-obDir & hun famler seg frem &
file__trPath-obRefl-obDir & hun filer seg frem &
fire__trPath-obRefl-obDir & de firer seg ned &
føle__trPath-obRefl-obDir & hun føler seg frem &
gisse__trPath-obRefl-obDir & hun gisser seg frem &
halte__trPath-obRefl-obDir & hun halter seg frem &
hangle__trPath-obRefl-obDir & de hangler seg gjennom perioden &
hinke__trPath-obRefl-obDir & hun hinker seg frem &
hufse__trPath-obRefl-obDir & hun hufser seg frem &
humpe__trPath-obRefl-obDir & vognen humper seg frem &
hute__trPath-obRefl-obDir & hun huter seg vekk &
hykle__trPath-obRefl-obDir & han hykler seg frem &
kave__trPath-obRefl-obDir & hun kaver seg frem &
krake__trPath-obRefl-obDir & hun kraker seg frem &
kraume__trPath-obRefl-obDir & hun kraumer seg frem &
kravle__trPath-obRefl-obDir & hun kravler seg frem &
kreke__trPath-obRefl-obDir & hun kreker seg frem &
krongle__trPath-obRefl-obDir & hun krongler seg frem &
krungle__trPath-obRefl-obDir & hun krungler seg frem &
krusle__trPath-obRefl-obDir & han krusler seg vekk &
lure__trPath-obRefl-obDir & tyvene lurer seg frem &
manøvrere__trPath-obRefl-obDir & hun manøvrerer seg frem &
orme__trPath-obRefl-obDir & lakeinene ormer seg frem &
padle__trPath-obRefl-obDir & hun padler seg frem &
pelle__trPath-obRefl-obDir & hun peller seg unna &
pigge__trPath-obRefl-obDir & hun pigger seg frem &
pitle__trPath-obRefl-obDir & kona pitler seg frem &
pløye__trPath-obRefl-obDir & gjengen pløyer seg frem &
presse__trPath-obRefl-obDir & hun presser seg frem &
ringle__trPath-obRefl-obDir & hun ringler seg frem &
ro__trPath-obRefl-obDir & hun ror seg til land &
sikksakke__trPath-obRefl-obDir & hun sikksakker seg frem &
skuve__trPath-obRefl-obDir & hun skuver seg frem &
skyve__trPath-obRefl-obDir & hun skyver seg frem &
slange__trPath-obRefl-obDir & krypskytterne slanger seg frem &
slite__trPath-obRefl-obDir & ekspedisjonen sliter seg frem &
slynge__trPath-obRefl-obDir & planterøttene slynger seg frem &
smyge__trPath-obRefl-obDir & hun smyger seg frem &
snegle__trPath-obRefl-obDir & ekspedisjonen snegler seg frem &
snike__trPath-obRefl-obDir & hun sniker seg frem &
snirkle__trPath-obRefl-obDir & hun snirkler seg frem &
sno__trPath-obRefl-obDir & opportunistene snor seg frem &
stake__trPath-obRefl-obDir & skiløperen staker seg frem &
stange__trPath-obRefl-obDir & oksen stanger seg frem &
stave__trPath-obRefl-obDir & skiløperen staver seg frem &
stavre__trPath-obRefl-obDir & hun stavrer seg frem &
stille__trPath-obRefl-obDir & hun stiller seg frem &
stiltre__trPath-obRefl-obDir & hun stiltrer seg frem &
stri__trPath-obRefl-obDir & hun strir seg frem &
stride__trPath-obRefl-obDir & de strider seg inn i bankerott &
stylte__trPath-obRefl-obDir & hun stylter seg frem &
styltre__trPath-obRefl-obDir & hun styltrer seg frem &
svinge__trPath-obRefl-obDir & hun svinger seg frem &
trekke__trPath-obRefl-obDir & hun trekker seg unna &
true__trPath-obRefl-obDir & hun truer seg frem &
truge__trPath-obRefl-obDir & hun truger seg frem &
tvinge__trPath-obRefl-obDir & hun tvinger seg frem &
vadre__trPath-obRefl-obDir & hun vadrer seg vekk &
vildre__trPath-obRefl-obDir & hun vildrer seg bort &
vime__trPath-obRefl-obDir & tullingen vimer seg bort &
vrikke__trPath-obRefl-obDir & selskapsdamen vrikker seg frem &
vringle__trPath-obRefl-obDir & hun vringler seg frem &
