anse__trScpr-obRefl-scObNrg-scPred & hun anser seg kompetent &
erkjenne__trScpr-obRefl-scObNrg-scPred &  han erkjenner seg skyldig &
erklære__trScpr-obRefl-scObNrg-scPred & hun erklærer seg kompetent &
føle__trScpr-obRefl-scObNrg-scPred & hun føler seg verdiløs &
gjøre__trScpr-obRefl-scObNrg-scPred & hun gjør seg valgbar &
holde__trScpr-obRefl-scObNrg-scPred & hun holder seg varm &
kalle__trScpr-obRefl-scObNrg-scPred & hun kaller seg kompetent &
kjenne__trScpr-obRefl-scObNrg-scPred & hun kjenner seg trygg &
nekte__trScpr-obRefl-scObNrg-scPred & hun nekter seg ansvarlig &
spørre__trScpr-obRefl-scObNrg-scPred & dommeren spør seg ferdig &
stille__trScpr-obRefl-scObNrg-scPred & hun stiller seg forstående &
