blåse__impers & det blåser &
brake__impers & det braker &
brenne__impers & det brenner &
brise__impers & det briser &
brumle__impers & det brumler &
brydde__impers & det brydder etter plogen &
bråke__impers & det bråker &
buldre__impers & det buldrer &
dage__impers & det dager &
dages__impers & det dages &
demre__impers & det demrer &
dimme__impers & det dimmer &
dise__impers & det diser &
dogge__impers & det dogger &
dryppe__impers & det drypper &
drønne__impers & det drønner &
dugge__impers & det dugger &
dundre__impers & det dundrer &
dure__impers & det durer &
duskregne__impers & det duskregner &
dønne__impers & det dønner &
ebbe__impers & det ebber &
flø__impers & det flør &
fossregne__impers & det fossregner &
gry__impers & det gryr &
gråne__impers & det gråner &
gufse__impers & det gufser &
gule__impers & det guler &
guste__impers & det guster &
hagle__impers & det hagler &
hølje__impers & det høljer &
høljeregne__impers & det høljeregner &
høljregne__impers & det høljregner &
ise__impers & det iser &
klarne__impers & det klarner &
klikke__impers & det klikker &
klirre__impers & det klirrer &
klukke__impers & det klukker &
klunke__impers & det klunker &
klynke__impers & det klynker &
knake__impers & det knaker &
knalle__impers & det knaller &
knase__impers & det knaser &
knatre__impers & det knatrer &
knatte__impers & det knatter &
knitre__impers & det knitrer &
krasle__impers & det krasler &
krisle__impers & det krisler &
kritle__impers & det kritler &
kule__impers & det kuler &
kvakke__impers & det kvakker &
kvelde__impers & det kvelder &
letne__impers & det letner &
linne__impers & det linner &
ljome__impers & det ljomer &
lugge__impers & det lugger &
lyne__impers & det lyner &
lysne__impers & det lysner &
løye__impers & det løyer &
morgne__impers & det morgner &
mulne__impers & det mulner &
myldre__impers & det myldrer &
mørkne__impers & det mørkner &
overskye__impers & det overskyer &
regne__impers & det regner &
rekne__impers & det rekner &
rime__impers & det rimer &
ringe__impers & det ringer &
runge__impers & det runger &
ryke__impers & det ryker &
sildre__impers & det sildrer &
silregne__impers & det silregner &
siregne__impers & det siregner &
sisle__impers & vannet sisler &
skumre__impers & det skumrer &
sludde__impers & det sludder &
sluddregne__impers & det sluddregner &
smelle__impers & det smeller &
sne__impers & det sner &
sno__impers & det snor &
snø__impers & det snør &
somres__impers & det somres &
sprutregne__impers & det sprutregner &
spørs_impers & det spørs &
stilne__impers & det stilner &
storme__impers & det stormer &
stridregne__impers & det stridregner &
striregne__impers & det striregner &
styrtregne__impers & det styrtregner &
støve__impers & det støver &
surkle__impers & det surkler &
suse__impers & det suser &
svartne__impers & det svartner &
svi__impers & det svir &
tilskye__impers & det tilskyer &
tordne__impers & det tordner &
trekke__impers & det trekker &
tuske__impers & det tusker &
tusle__impers & det tusler &
tusse__impers & det tusser &
tø__impers & det tør &
ulme__impers & det ulmer &
vintres__impers & det vintres &
vrimle__impers & det vrimler &
våres__impers & det våres &
yre__impers & det yrer &
øsregne__impers & det øsregner &
