bruse-i__impersObl-oblN & det bruser i hodet &
dages-for__impersObl-oblN & det dages for oss &
demre-av__impersObl-oblN & det demrer av dag &
demre-for__impersObl-oblN & det demrer for meg &
eime-av__impersObl-oblN & det eimer av tørket tang &
flimre-for__impersObl-oblN & det flimrer for øynene &
glitre-i__impersObl-oblN & det glitrer i krystallet &
gå-i__impersObl-oblN & det går i døren &
hagle-med__impersObl-oblN & det hagler med beskyldninger &
ise-i__impersObl-oblN & det iser i nerven &
kile__impersObl-oblN & det kiler i nesen &
kime__impersObl-oblN & det kimer i klokker &
kisle__impersObl-oblN & det kisler i hodebunnen &
kitle-i__impersObl-oblN & det kitler i hodebunnen &
klapre-i__impersObl-oblN & det klaprer i skjellettdelene &
klinge-i__impersObl-oblN & det klinger i klokkene &
klirre-i__impersObl-oblN & det klirrer i glassene &
knake-i__impersObl-oblN & det knaker i stillaset &
knalle-i__impersObl-oblN & det knaller i ammunisjonslageret &
knirke-i__impersObl-oblN & det knirker i plankene &
knyste-i__impersObl-oblN & det knyster i ham &
krase-i__impersObl-oblN & det kraser i delene &
krible-i__impersObl-oblN & det kribler i tærne &
krisle-i__impersObl-oblN & det krisler i kroppen &
kry-av__impersObl-oblN & det kryr av maur &
kvekke-i__impersObl-oblN & det kvekker i ham &
kveppe-i__impersObl-oblN & det kvepper i ham &
lakke-mot__impersObl-oblN & det lakker mot natt &
li-mot__impersObl-oblN & det lir mot dag &
li-på__impersObl-oblN & det lir på dag &
ljome-i__impersObl-oblN & det ljomer i klokkene &
murre-i__impersObl-oblN & det murrer i befolkningen &
myldre-av__impersObl-oblN & det myldrer av utkledde personer &
plinge-i__impersObl-oblN & det plinger i bollen &
prikke-i__impersObl-oblN & det prikker i armen &
rable-for__impersObl-oblN & det rabler for ham &
rasle-i__impersObl-oblN & det rasler i løvet &
ratle__impersObl-oblN & det ratler mellom stenene &
ringe__impersObl-oblN & det ringer i klokkene &
rumle-i__impersObl-oblN & det rumler i maven &
ruske-i__impersObl-oblN & det rusker i trærne &
sikle__impersObl-oblN & det sikler &
single-i__impersObl-oblN & det singler i glass &
sitre-i__impersObl-oblN & det sitrer i kroppen &
skorte-på__impersObl-oblN & det skorter på vann &
skrelle-i__impersObl-oblN & det skreller i fjellet &
skvalpe-i__impersObl-oblN & det skvalper i spannet &
skvette-i__impersObl-oblN & det skvetter i gutten &
slamre-i__impersObl-oblN & det slamrer i dørene &
slå__impersObl-oblN & det slår i vinduene &
smelle-i__impersObl-oblN & det smeller i dørene &
sprake-i__impersObl-oblN & det spraker i kvistene &
sprekke-i__impersObl-oblN & det sprekker i glasset &
stinke-av__impersObl-oblN & det stinker av fiskelim &
storme__impersObl-oblN & det stormer på kysten &
strømme-med__impersObl-oblN & det strømmer med sympati &
stunde-mot__impersObl-oblN & det stunder mot aften &
støkke-i__impersObl-oblN & det støkker i kona &
sukke__impersObl-oblN & det sukker i bølgene i vannkanten &
surre-i__impersObl-oblN & det surrer i boksen &
svartne-for__impersObl-oblN & det svartner for ham &
svi__impersObl-oblN & det svir i hodebunnen &
svimle-for__impersObl-oblN & det svimler for gutten &
svimre__impersObl-oblN & det svimrer for øynene &
svuppe-i__impersObl-oblN & det svupper i skoene &
synge-i__impersObl-oblN & det synger i stålet &
synge__impersObl-oblN & det synger i fjellene &
søkke-i__impersObl-oblN & det søkker i ham &
ulme-i__impersObl-oblN & det ulmer i skogbunnen &
verke-i__impersObl-oblN & det verker i leddene &
vrimle-av__impersObl-oblN & det vrimler av folk &
vrimle-med__impersObl-oblN & det vrimler med folk &
yre-av__impersObl-oblN & det yrer av deltagere &
