berøre__trObl-oblPRTOFob & tungen berører ham i ansiktet &
dikke__trObl-oblPRTOFob & mannen dikker hunden på snuten &
dolke__trObl-oblPRTOFob & han dolker meg i ryggen &
dulte__trObl-oblPRTOFob & jeg dulter ham i ryggen &
dunke__trObl-oblPRTOFob & han dunker dem i ryggen &
føle__trObl-oblPRTOFob & hun føler meg i ansiktet &
glattstryke__trObl-oblPRTOFob & vi glattstryker skjorten i kraven &
hogge__trObl-oblPRTOFob & jeg hogger ham i foten &
hugge__trObl-oblPRTOFob & jeg hugger ham i foten &
kakke__trObl-oblPRTOFob & hun kakker meg i hodet &
kile__trObl-oblPRTOFob & den kiler henne i ansiktet &
kisle__trObl-oblPRTOFob & stoffet kisler henne i ansiktet &
kitle__trObl-oblPRTOFob & stoffet kitler henne i ansiktet &
klappe__trObl-oblPRTOFob & hun klapper han i ansiktet &
klapse__trObl-oblPRTOFob & hun klapser ham i ansiktet &
klaske__trObl-oblPRTOFob & hun klasker ham i ansiktet &
klipe__trObl-oblPRTOFob & hun kliper ham i rumpa &
klore__trObl-oblPRTOFob & katten klorer jenta i ansiktet &
klubbe__trObl-oblPRTOFob & hun klubber ham i ansiktet &
klype__trObl-oblPRTOFob & hun klyper ham i ansiktet &
klø__trObl-oblPRTOFob & myggstikkene klør dem i ansiktet &
klå__trObl-oblPRTOFob & mannen klår henne på ryggen &
knekke__trObl-oblPRTOFob & han knekker grenen på midten &
knipse__trObl-oblPRTOFob & han knipser gutten i ansiktet &
komme_trObl-oblPRTOFob & politiet kommer de kriminelle i forkjøpet & 
krille__trObl-oblPRTOFob & skjorta kriller ham på ryggen &
kysse__trObl-oblPRTOFob & hun kysser ham i ansiktet &
le__trObl-oblPRTOFob & hun ler ham i ansiktet &
lugge__trObl-oblPRTOFob & hun lugger ham i håret &
nufse__trObl-oblPRTOFob & katten nufser henne i ansiktet &
pille__trObl-oblPRTOFob & hun piller ham i ansiktet &
pisse__trObl-oblPRTOFob & han pisser dem i ansiktet &
prikke__trObl-oblPRTOFob & hun prikker ham i ansiktet &
ruske__trObl-oblPRTOFob & vinden rusker dem i ansiktet &
skalle__trObl-oblPRTOFob & hun skaller ham i ansiktet &
skjære__trObl-oblPRTOFob & hun skjærer ham i håndleddet &
skrubbe__trObl-oblPRTOFob & hun skrubber dem i ansiktet &
skyte__trObl-oblPRTOFob & hun skyter ham i ansiktet &
sleike__trObl-oblPRTOFob & hunden sleiker henne i ansiktet &
slikke__trObl-oblPRTOFob & hunden slikker henne i ansiktet &
slå__trObl-oblPRTOFob & politifolkene slår dem i ansiktet &
smaske__trObl-oblPRTOFob & hun smasker gutten i ansiktet &
smekke__trObl-oblPRTOFob & hun smekker ham på hånden &
sparke__trObl-oblPRTOFob & hun sparker ham i skrittet &
stikke__trObl-oblPRTOFob & prinsessen stikker seg på nålen &
stryke__trObl-oblPRTOFob & hun stryker ham over ansiktet &
såre__trObl-oblPRTOFob & han sårer soldaten i foten & 
ta__trObl-oblPRTOFob & vinden tar dem i ansiktet &
treffe__trObl-oblPRTOFob & pilen treffer ham i ansiktet &
tråkke__trObl-oblPRTOFob & deltageren tråkker dommeren i ansiktet &
tørke__trObl-oblPRTOFob & vi tørker statuen på baksiden &
vafle__trObl-oblPRTOFob & hun vafler ham i ansiktet &
