bite-i__trScpr-scPPrefl & han biter i seg kritikken &
bre-på__trScpr-scPPrefl & hun brer på seg teppet &
ergre-på__trScpr-scPPrefl & han ergrer på seg et maveonde &
erte-på__trScpr-scPPrefl & han erter på seg vaktene &
ete-i__trScpr-scPPrefl & de eter i seg fisken &
gafle-i__trScpr-scPPrefl & hun gafler i seg maten &
glefse-i__trScpr-scPPrefl & hunden glefser i seg maten &
gnafse-i__trScpr-scPPrefl & han gnafser i seg maten &
grabbe-til__trScpr-scPPrefl & han grabber til seg gjenstandene &
grafse-til__trScpr-scPPrefl & hun grafser til seg pengene &
gulke-i__trScpr-scPPrefl & han gulker det i seg &
jafse-i__trScpr-scPPrefl & han jafser i seg maten &
kare-til__trScpr-scPPrefl & hun karer til seg maten &
karre-til__trScpr-scPPrefl & hun karrer til seg maten &
kle-av__trScpr-scPPrefl & hun kler av seg jakken &
kle-på__trScpr-scPPrefl & hun kler på seg jakken &
krafse-til__trScpr-scPPrefl & hun krafser til seg maten &
lepje-i__trScpr-scPPrefl & katten lepjer i seg melken &
levne-etter__trScpr-scPPrefl & de må levne noe etter seg &
lire-av__trScpr-scPPrefl &  hun lirer av seg leksen &
nappe-til__trScpr-scPPrefl & hun napper til seg brødet &
naske-til__trScpr-scPPrefl & hun nasker til seg maten &
rane-til__trScpr-scPPrefl & hun raner til seg maten &
rappe-til__trScpr-scPPrefl & hun rapper til seg pengene &
slafse-i__trScpr-scPPrefl & hun slafser i seg maten &
sleike-i__trScpr-scPPrefl & katten sleiker i seg maten &
sluke-i__trScpr-scPPrefl &  hun sluker i seg maten &
slurpe-i__trScpr-scPPrefl &  hun slurper i seg suppen &
snakke-til__trScpr-scPPrefl & han snakker til seg fordeler &
snappe-til__trScpr-scPPrefl & hun snapper til seg vinflasken &
snaske-til__trScpr-scPPrefl & hun snasker til seg vinflasken &
snike-til__trScpr-scPPrefl & han sniker til seg oppdraget &
snoke-til__trScpr-scPPrefl & han snoker til seg oppdraget &
snuske-til__trScpr-scPPrefl & han snusker til seg oppdraget &
snylte-til__trScpr-scPPrefl & opportunistene snylter til seg oppdraget &
spandere-på__trScpr-scPPrefl & hun spanderer på seg en ny jakke &
spise-i__trScpr-scPPrefl & hun spiser i seg maten &
svindle-til__trScpr-scPPrefl & de svindler til seg fortjenesten &
tuske-til__trScpr-scPPrefl & de tusker til seg varene &
tvinge-til__trScpr-scPPrefl & hun tvinger til seg jobben &
tylle-i__trScpr-scPPrefl & hun tyller drikken i seg &
